### ISSUE TITLE
[Bug] Hoppers don't work properly 

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#106]
**Describe the bug**
Hoppers don't fully empty themselves into a target block (chest, furnace, etc)
**To Reproduce**
Put a hopper connected to a target block.

**Expected behavior**
The hopper should empty itself into the target block.

**Comment by MrIvanPlays** [comment]
Probably caused by one of newest emc ported patches.
I've removed it and im going to commit now

**Comment by toinouH** [comment]
No, on discord he says that the bug existed before but he has forgotten to report it @MrIvanPlays

**Comment by toinouH** [comment]
![image](https://user-images.githubusercontent.com/64892431/90318828-7fe10180-df33-11ea-9567-a6ec5f813ba7.png)

**Comment by MrIvanPlays** [comment]
Well then what are the settings related to hoppers?

**Comment by RealGatt** [comment]
![image](https://user-images.githubusercontent.com/1311244/90332053-f8f85b80-dffc-11ea-80a0-014b0c379c2d.png)

This setup allows the hoppers to tick and update.

**Comment by MrIvanPlays** [comment]
ok here are my testing results
hoppers transfering to chests are fine, but hoppers to furnaces doesn't

any other block I need to check? 

EDIT: Hoppers transfering to hoppers is fine too

**Comment by RealGatt** [comment]
Not that we've found. It's specifically furnaces with `{lit:true}`

**Comment by MrIvanPlays** [comment]
> It's specifically furnaces with `{lit:true}`

Nope, it doesn't even work with not lit ones

**Comment by RealGatt** [comment]
Interesting. Furnaces on our server works until the furnace is lit
![image](https://user-images.githubusercontent.com/1311244/90332186-5b9e2700-dffe-11ea-92df-ad82d2902f86.png)

**Comment by MrIvanPlays** [comment]
what version?

**Comment by RealGatt** [comment]
6237d7d 1.16.2
![image](https://user-images.githubusercontent.com/1311244/90332266-c94a5300-dffe-11ea-85f8-b2ce9232095a.png)

**Comment by toinouH** [comment]
@Titaniumtown Can you give us the first version that you remember with that bug ?

**Comment by MrIvanPlays** [comment]
LMK if https://github.com/YatopiaMC/Yatopia/actions/runs/210736955 fixed ur issues :) 

EDIT: [this](https://github.com/YatopiaMC/Yatopia/actions/runs/210741859) build for 1.16.1

**Comment by Titaniumtown** [comment]
It still seems to not work

**Comment by MrIvanPlays** [comment]
Are you sure? Cuz like I performed a test and it worked fine for me.
Also check your settings.

**Comment by Titaniumtown** [comment]
I'll look at my settings rn

**Comment by Titaniumtown** [comment]
It works.
