### ISSUE TITLE
IMPORTANT - abnormal tps loss

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#11]
Hi, This morning around 13:30 pm I updated the server to the latest build of Yapfa. After installing this the server is practically dying ... drops of absurd tps and slow chunks in the upload. I also tried to put the penultimate build but it still lags

**Comment by NovaPixell** [comment]
UPDATE: I think I solved it by deleting all the files inside the "cache" folder and running build 85. Please check this problem because it is very serious.

**Comment by tr7zw** [comment]
Eh can you create spark timings of these lags? Build 85 is a month old and since then a lot of stuff got changed in Paper/Tuinity/yapfa, so not really anything I could pinpoint currently.

**Comment by NovaPixell** [comment]
Just made now! With 55 players I had 10/12 tps, absurd this thing
https://timings.aikar.co/?id=0bb219fc6a45469cb99f6925d18dc1db

**Comment by NovaPixell** [comment]
I really see that players jerk when they move.

**Comment by tr7zw** [comment]
Minecraft::world - Scheduled Blocks - Ticking (SELF)
count(1195)  total(48.78% 98.353s, 164.61% of tick)
avg(82.30ms per - 82.30ms/1.00 per tick)
Seems like Scheduled Block ticks, but without spark timings, I can't tell you whats going on there.  But I'll quickly do an upstream update, maybe something was broken in tuinity.

**Comment by NovaPixell** [comment]
It's fine! But will you do it tomorrow?

**Comment by tr7zw** [comment]
Well the upstream update is running, and you then can test with that + spark.

**Comment by NovaPixell** [comment]
If it's not a problem, could you do it within half an hour?

**Comment by NovaPixell** [comment]
I read that on tuinity 13 hours ago they made an update, is that probably why?

**Comment by NovaPixell** [comment]
Wait but what is spark?

**Comment by NovaPixell** [comment]
OT: I noticed that villagers die suffocated alone, is this normal?

**Comment by NovaPixell** [comment]
Excuse me, can you tell me how much is missing?

**Comment by tr7zw** [comment]
It's currently locally building yapfa with the new changes, gimme ~5 more mins to push, depending on if there is any conflict of the patches.

**Comment by NovaPixell** [comment]
Okay, thank you very much

**Comment by tr7zw** [comment]
Ok commit is up, takes a few min to build by the CI, and https://github.com/lucko/spark this is spark, if it is still behaving please create some timings using ``/spark profiler``

**Comment by NovaPixell** [comment]
Nice! Thanks!

**Comment by NovaPixell** [comment]
I loaded the build but must run the "/ spark profiler" command if I don't get it wrong? If I run it it doesn't exist

**Comment by tr7zw** [comment]
Well you need to install spark^^

**Comment by NovaPixell** [comment]
Ah okok, I thought it was integrated! Nice! I will let you know tomorrow with the maximum server load how it goes! Thanks to the availability

**Comment by NovaPixell** [comment]
Meanwhile, these are the current timings:
https://timings.aikar.co/?id=a1936f4ba3b049029f810e4fd5424dae

**Comment by tr7zw** [comment]
Huh looks like some anti lag plugin or so printing that. Also quickly took a look at the plugin list, you can remove "ZeroTickFarmBlocker" since that's a feature of Paper. Also Still scheduled block ticks really high(can't tell what blocks without spark timings), and you have 7.4k tiles and 1.3k entities in just 37 chunks? Thats sounds like mega storage systems with lots of hoppers/tnt dupers or so?

**Comment by NovaPixell** [comment]
I installed spark, but with the "/spark profiler" command how can I have timings? Can you help me?

**Comment by NovaPixell** [comment]
Spark timings: https://spark.lucko.me/#NylACwbgYd

**Comment by NovaPixell** [comment]
Ok ... found the problem .. our command block expert left many command blocks active on the server ... oh well I was very bad. I'm really sorry bro and thank you for the help!

**Comment by NovaPixell** [comment]
While I wanted to ask you, why do villagers die on their own suffocating?

**Comment by tr7zw** [comment]
Eh that could be the current problem in 1.15 of villagers kinda disappearing(thats why it prints villager deaths to the console, to kinda keep track of what might be happening to them). For reffrence: https://bugs.mojang.com/browse/MC-153904 If they are infact suffocating, you could maybe turn on "disableEntityStuckChecks" in the yapfa config, but that will prevent everything to take suffocation damage.
