### ISSUE TITLE
[Bug] Loading some chunks lags the client

### ISSUE THREAD

**Issue by ishland** [tr7zw/YAPFA#112]
**Describe the bug**
Loading certain chunks lags the client and makes it unresponsive for some seconds. 

**To Reproduce**
Just walk around your world. 

**Expected behavior**
Should not lag the client

**Server Setup**
Server Specifications: 
Using AdoptOpenJDK 14.0.2+12 HotSpot

**/version output**
```
This server is running Yatopia version git-Yatopia-"c06bac8" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
Previous version: git-Paper-"b91d964b1" (MC: 1.16.1)
You are 2 version(s) behind
```

**Plugins used**
```
Plugins (20): Barrels, CS-CoreLib, JukeBox, MinecraftSP, MineTinker, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SandtoQuartz, ServerMSPT, Slimefun, spark, TitleManager*, Vault, ViaBackwards, ViaVersion, XPConomy
```

**Additional context**
The client is spamming `Received invalid biome id: -1` in logging system.

**Comment by MrIvanPlays** [comment]
Is this behavior happening after upgrading your world from 1.16.1 ? 
Also if you're generating chunks chunk generation looks slow for the client. And try updating to latest yatopia as we updated paper  as paper did some changes with chunks. 

EDIT: I also have some lag spikes and fps drop with client, but the vanilla client is very unoptimized and we need optifine for life.

**Comment by ishland** [comment]
After upgrading and join, this happens immediately when it is joining world. 
This is a generated flat world area in Multiverse. 
![image](https://user-images.githubusercontent.com/30385023/90334222-cbacad00-dffe-11ea-94bc-04b4cdc88572.png)

**Comment by MrIvanPlays** [comment]
honestly try bumping upstream with this, we don't do any changes around chunk loading.

**Comment by ishland** [comment]
Alright and I will try to reproduce it on Tuinity and Paper

Currently reproducing on pure Yatopia

**Comment by toinouH** [comment]
I don't know if it could help but change the default value (2 or 4 I don't remeber) for an higher one if you can (for the client)
![image](https://user-images.githubusercontent.com/64892431/90334311-16adcc80-dfcd-11ea-98f3-5d8137120051.png)

**Comment by ishland** [comment]
> I don't know if it could help but change the default value (2 or 4 I don't remeber) for an higher one if you can

I dont have that much ram and it is not pulling a lot of ram but a generic lag

**Comment by MrIvanPlays** [comment]
> I dont have that much ram

which means you probably have some old cpu which can't handle newer versions.
just wait for optifine. this issue is not an issue from us or upstream

**Comment by ishland** [comment]
It is not lagging in other servers.
I allocated 3G of ram for Minecraft and running smoothly 70fps in other servers

**Comment by MrIvanPlays** [comment]
if updating yatopia doesn't change it then it is something with your terrain. again, out of scope, nothing we can do about.

**Comment by ishland** [comment]
This is completely not happening on vanilla

**Comment by ishland** [comment]
This is NOT happening on Tuinity. Please repoen
Running for about 10000 blocks away with no noticable lag.

**Comment by toinouH** [comment]
(I think he will). You see all different upstream, can you do some test to tell us wich upstream is the problem ?
The check means that the bug doesn't exist in the upstream.
- [x] Vanilla
- [ ] Paper 
- [x] tuinity
- [ ] Akarin
- [ ] Empirecraft
- [ ] Origami
- [ ] Purpur
- [ ] Rainforest

**Comment by MrIvanPlays** [comment]
try reproducing with latest yatopia. if you can, im going to try it on my 1.16.1 generated world.
if I can reproduce it too, im going to reopen the issue. otherwise there are signs that this isn't exactly yatopia's issue.

**Comment by MrIvanPlays** [comment]
I tried it anyway, and I can't reproduce it.

**Comment by toinouH** [comment]
Please join our discord, it will be easier to talk https://discord.io/YatopiaMC

**Comment by ishland** [comment]
It is still lagging after upgrading
Here is the affected world: https://drive.google.com/file/d/1ePzepP4MQqm6RnCpsTILhaTwagbkMzUl/view?usp=sharing
And also timings link: https://timings.aikar.co/?id=ffc360beb4a2429991197cf82c45f96d

**Comment by ishland** [comment]
Possible solutions: 
1. Supress sending -1 biome ids and replace with 0
2. Replace biome ids with 0 in chunks
3. Regenerate biome ids

**Comment by ishland** [comment]
For anyone who encounter this issue, use this: https://github.com/ishlandbukkit/BiomeIDFix/

**Comment by MrIvanPlays** [comment]
> For anyone who encounter this issue, use this: https://github.com/ishlandbukkit/BiomeIDFix/

How about we implement this fix directly in yatopia?
