### ISSUE TITLE
[Bug] Hoppers are not pulling items into entities correctly

### ISSUE THREAD

**Issue by OEUG99** [tr7zw/YAPFA#114]
**Describe the bug**
Hoppers are not pulling items into entities correctly

**To Reproduce**
1) Place a hopper above blocks/entity. (in the case of  brewing stands you place on the sides)
2) place items into hopper

List of blocks/entities that have issues
1) Composters
2) chest-minecarts
3) hopper-minecarts
3) brewing stands (they work but are buggy)

**Expected behavior**
Vanilla

**Additional context**
Brewing stands seem to work, except they are just extremely delayed with the pull.
I'm running the latest build of Yatopia, the hopper patch from yesterday corrected
some of the issues w/ hoppers but not all of them.

**Comment by MrIvanPlays** [comment]
Composters should be resolved from the patch yesterday.
minecarts are probably caused by empirecraft's patch will look at it

**Comment by MrIvanPlays** [comment]
let me know if [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212100529) build fixes it ([this](https://github.com/YatopiaMC/Yatopia/actions/runs/212102571) for 1.16.1)

**Comment by OEUG99** [comment]
> let me know if [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212100529) build fixes it ([this](https://github.com/YatopiaMC/Yatopia/actions/runs/212102571) for 1.16.1)
Just gave it a run, the chest-minecarts & hopper-carts appear to be working. composters aren't fuctioning like vanilla though, along with brewing stands being delayed still.

**Comment by MrIvanPlays** [comment]
> composters aren't fuctioning like vanilla though, along with brewing stands being delayed still.

May you share your settings with us?

**Comment by OEUG99** [comment]
> > composters aren't fuctioning like vanilla though, along with brewing stands being delayed still.
> 
> May you share your settings with us?

I have not modified any server files and just used the default generated ones. No plugins. I created a isolated test server for this bug report.

**Comment by MrIvanPlays** [comment]
just checked and I can't seem to find ANY changes which are made by us about composters and brewing stands.
you may wanna try reprodce it on paper and bump on them if it is reproduced there.

**Comment by OEUG99** [comment]
> just checked and I can't seem to find ANY changes which are made by us about composters and brewing stands.
> you may wanna try reprodce it on paper and bump on them if it is reproduced there.

I am unable to reproduce it on paper-135, the issue seems to be exclusive to Yatopia

**Comment by OEUG99** [comment]
I created a short video demonstrating the problem, and comparing it to the vanilla fuctionality where the composter fills all the way.
https://youtu.be/noTsxkxCHBw

**Comment by MrIvanPlays** [comment]
I found what's causing it and I'm going to commit my fixes soon. I just need to test another fix I've made

**Comment by MrIvanPlays** [comment]
Try [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212488661) build for 1.16.2 and [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212499308) build for 1.16.1

**Comment by MrIvanPlays** [comment]
looks like github's being a piece of shit again and didn't want to upload the artifact so instead you have to wait for the next build or just try and test 1.16.2 

EDIT: or use [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212489024) build, its the same but not the same branch

**Comment by OEUG99** [comment]
> looks like github's being a piece of shit again and didn't want to upload the artifact so instead you have to wait for the next build or just try and test 1.16.2
> 
> EDIT: or use [this](https://github.com/YatopiaMC/Yatopia/actions/runs/212489024) build, its the same but not the same branch

Thank you, It's fixed!
