### ISSUE TITLE
[Bug] Regular Villagers have Wandering Trader AI with the "simplerVillagerBehavior" option enabled

### ISSUE THREAD

**Issue by RealGatt** [tr7zw/YAPFA#125]
**Expected behavior**
At night, Villagers should behave like regular villagers.

**Observed behavior**
At night, Villagers drink an Invisibility Potion, like Wandering Traders. During the day, the Villager drinks milk to reverse the effects.
![image](https://user-images.githubusercontent.com/1311244/90583311-2f0f2880-e213-11ea-9583-172f16590ea7.png)

**Steps to reproduce (if known)**
Enable "simplerVillagerBehavior" in the yatopia.yml file. Spawn a villager, set time to night.

**Installed plugins**
![image](https://user-images.githubusercontent.com/1311244/90583420-75648780-e213-11ea-80fe-a1d582a1ead2.png)

**Version**
![image](https://user-images.githubusercontent.com/1311244/90583442-801f1c80-e213-11ea-9d6c-afcba57677a5.png)

**Additional context**
Setting the "simplerVillagerBehavior" to false immediately resolves the issue.

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.2/patches/server/0019-Option-for-simpler-Villagers.patch#L60
