### ISSUE TITLE
[Bug] Advancements being reset randomly on players.

### ISSUE THREAD

**Issue by OEUG99** [tr7zw/YAPFA#126]
**Observed behavior**

This has happened twice now, a player gets kicked from the server for "you logged in from another location" and
then their advancement file can't be parsed.

Heres an example from logs:
https://pastebin.com/Me8HabXa

Worth noting, the player isn't actually logging in from another location when the kick randomly occurs.

**Installed plugins**

https://i.imgur.com/j8e50O4.png

**Version**

https://i.imgur.com/EiJkfxY.png

**Comment by Disguys** [comment]
by the way, Yes, I was also informed by some players that their achievements are randomly reset

**Comment by Disguys** [comment]
I think what is happening because of async-advancements

**Comment by MrIvanPlays** [comment]
honestly try bumping rainforest with this. 
you can try disabling async advancements untill the issue is resolved by proximyst if you report it there.

**Comment by OEUG99** [comment]
> honestly try bumping rainforest with this.
> you can try disabling async advancements untill the issue is resolved by proximyst if you report it there.

I dont think that is the issue, I had async advancements disabled
`async-advancements: false`

**Comment by TheFaser** [comment]
I agree, on the latest versions of the kernel, this happens often and happens on the micro-lags of the server, when the player reboots or logs in from the second minecraft

**Comment by Proximyst** [comment]
Fixed on latest Rainforest.

**Comment by MrIvanPlays** [comment]
> Fixed on latest Rainforest.

Thank you, im going to update it right now.

**Comment by MrIvanPlays** [comment]
That's why I don't like updating upstream too much... 
![image](https://img.mrivanplays.com/WindowsTerminal_baFxOu4cSr.png) 
now I have to reimplement the whole patch....

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/40645612cfaeb3686ad88570585f1299704e2426

**Comment by Titaniumtown** [comment]
This just happened to my friend.
