### ISSUE TITLE
Minecart do not suffer collisions

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#136]
**Expected behavior**
Minecart do not suffer collisions

**Observed behavior**
Minecart do not suffer collisions if you try to move them

**Steps to reproduce (if known)**
In my case by disabling collisions in "water-ambient", "water-creature" and "pillagers", in yatopia.yml file, Minecart does not suffer collisions. 

**Installed plugins**
https://gyazo.com/f1a677ccd3b38dc67a558c8e6d3f34dc

**Version**
Yatopia Version: git-Yatopia-48398c2 (1.16.1)

**Comment by MrIvanPlays** [comment]
Tell me if [this](https://github.com/YatopiaMC/Yatopia/actions/runs/218396819) build solves your problem ([this](https://github.com/YatopiaMC/Yatopia/actions/runs/218382776) for 1.16.2)

**Comment by NovaPixell** [comment]
Fixed 👍
