### ISSUE TITLE
after teleporting to nether, strange things happen

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#137]
**Expected behavior**
Normal

**Observed behavior**
After I teleport to nether, I appear without things at zero coordinates for a few seconds

**Steps to reproduce (if known)**
Teleported to nether via a portal
video about the bug - https://youtu.be/mKRRtmgCVhg

**Installed plugins**
https://imgur.com/a/7XQXNL6

**Version**
git-Yatopia-"483c794" (MC: 1.16.2)

**Comment by MrIvanPlays** [comment]
you are experiencing network lag; your ping goes up to 400ms
