### ISSUE TITLE
enderman run into the water

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#138]
**Expected behavior**
not run into the water

**Steps to reproduce (if known)**
video about the bug - https://youtu.be/BKf2vQFamkI

**Installed plugins**
https://imgur.com/a/7XQXNL6

**Version**
git-Yatopia-"483c794" (MC: 1.16.2)

**Comment by MrIvanPlays** [comment]
report to paper, this is from their pathfinder optimizations.
it may be vanilla too, but this is low chance.

**Comment by Disguys** [comment]
I left a report - https://github.com/PaperMC/Paper/issues/4165

**Comment by kennytv** [comment]
Stop forwarding people to create issues somewhere if you haven't tested their validity/origin for yourself. This is a Vanilla issue.

**Comment by MrIvanPlays** [comment]
I forward them whenever I see there isn't a patch modifying the behavior of the reported thing.

**Comment by kennytv** [comment]
Then don't do that please, it's evidently a faulty approach... Tell people to actually **test** if the problem persists on Paper/Spigot/Vanilla and don't just plainly, _very_ confidently say "report to paper, this is from their pathfinder optimizations."

**Comment by MrIvanPlays** [comment]
ok
accidental close

**Comment by MrIvanPlays** [comment]
We may fix this, although it is a low priority since it isn't something game breaking.

**Comment by toinouH** [comment]
I think this the bug: https://bugs.mojang.com/browse/MC-185977

**Comment by Titaniumtown** [comment]
Can this still be reproduced on the latest build?

**Comment by Titaniumtown** [comment]
I'm going to close this issue. Feel free to reopen it, if it can still be reproduced.

**Comment by Disguys** [comment]
However, after checking this error on the latest version of Yatopia, I made sure that it is still relevant, I apologize in advance for such a long answer.

**Comment by Disguys** [comment]
I think that this problem should be opened again

**Comment by ishland** [comment]
If you still have this issue, feel free to open a new issue.
