### ISSUE TITLE
Chunks disappearing when trying to break a block inside of is temporarily

### ISSUE THREAD

**Issue by Alexander3a** [tr7zw/YAPFA#145]
**Expected behavior**
So i am breaking blocks and the bug shown in the vid happens

**Observed behavior**
after breaking some blocks in the chuck the Chunk disappears

**Steps to reproduce (if known)**
it started happening only after i updated to the newest version never happend bevor seems like its a bug with the update not with any plugin

**Installed plugins**
Plugins (14): CoreProtect, DupeBull, Essentials, EssentialsChat, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NerfPhantoms, PL-Hide, ProtocolLib, SuperVanish, Vault, WorldEdit

**Version**
showen in the vid is also the newest version as of now
https://youtu.be/k7AzkFWQXxE

**Additional context**
only happens with the newest version does not happen in the version i downloaded on the 20th

**Comment by MrIvanPlays** [comment]
Try reproducing without modded client.

**Comment by Alexander3a** [comment]
![2020-08-23_21 43 45](https://user-images.githubusercontent.com/47086788/90987246-bf3dcc80-e589-11ea-8adb-881077764550.png)
Still happens i am on complete vannila
only differnce that the chucks instantly update because on the modded i used sodium what made it so the chunks where invisable at first.
My horse for example died from this because it fell though it too so its a server side issu not a client side one otherwise i woud not take fall damage

**Comment by TheFaser** [comment]
I agree, only on this core we had the same

**Comment by toinouH** [comment]
@TheFaser @Alexander3a Is it in 1.16.1 or 1.16.2 ?

**Comment by TheFaser** [comment]
This happens on 1.16.2

**Comment by RealGatt** [comment]
![image](https://user-images.githubusercontent.com/1311244/91003641-39fff980-e615-11ea-8796-72af86a1e328.png)

Can confirm also occurring on d5b65a9. Entities and players can fall through the chunk, but blocks cannot be interacted with.

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/e1a085de4c7559a982a915d1b199d9a3a079f38b
