### ISSUE TITLE
Hoppers don't put items into minecart containers

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#148]
**Expected behavior**
Hopper directed into chest- or hopper-minecart puts its items into minecart.

**Observed behavior**
Hopper directed into chest- or hopper-minecart doesn't do anything with items inside of it, items stay in the hopper.

**Steps to reproduce (if known)**
1. Place rail and chest- or hopper-minecraft on it.
2. Place hopper, facing to rail block you placed in 1st step.

**Installed plugins**
![image](https://user-images.githubusercontent.com/64396538/91012697-efc04d80-e5ff-11ea-913e-841c3a1de232.png)
EPChat, EPModule and EveryWorldSpawn are my custom plugins, they don't do anything that might cause observed behavior, they don't register any listeners on InventoryEvent.

**Version**
![image](https://user-images.githubusercontent.com/64396538/91012856-3c0b8d80-e600-11ea-8e9f-7fdc40a4f752.png)
Note: the only modification I made to this version is replacing _assets/minecraft/lang/en\_us.json_ by russian version.

**Additional context**
Since this issue have my plugin list and custom modifications I made to Yatopia, I want to delete or make this issue shown only for yatopia developers, because I don't want to show these infos to anyone else. Is it possible?

**Comment by MrIvanPlays** [comment]
> custom modifications I made to Yatopia

**Comment by ishland** [comment]
Use unmodified version and try reproduce it again

**Comment by toinouH** [comment]
It might be reopened ONLY if you can confirm that happens with the latest unmodified version.

**Comment by metabrixkt** [comment]
Should I create new issue? I copied _*.yml_ and _server.properties_ from remote host where server is running to local directory, downloaded Yatopia-1.16.1-JDK8-paperclip.jar from releases, ran it using `/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar Yatopia-1.16.1-JDK8-paperclip.jar --nogui`
And I reproduced this bug without any plugins/modifications.
UPDATE: It also happens even if I stop server, remove _*.yml_ and start it again.

**Comment by MrIvanPlays** [comment]
okay I tried reproducing myself. first, how did you put the hopper above the minecart at first place? 
if you put it before and then put a minecart under it doesn't work, vanilla too. anything else you might waste our time with?

**Comment by metabrixkt** [comment]
I think you don't understand because my English is bad, I recorded a video to show you what I mean. https://mc.epserv.ru/media/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202020-08-24%2012:31:44.mp4

**Comment by metabrixkt** [comment]
Thanks, can this issue be hidden for everyone (except yatopia developers) or deleted when it's resolved? And approximately how long will it take to fix the bug?

**Comment by ishland** [comment]
Issues cannot be hidden or removed and isn't designed to be hidden or removed.

**Comment by metabrixkt** [comment]
ok, can I delete plugin list image from the first message as it isn't needed now?

**Comment by MrIvanPlays** [comment]
if you delete anything we're marking this report invalid.

**Comment by metabrixkt** [comment]
approximately how long will it take to fix the bug? my players have many farms and these farms got broken when I switch from paper to yatopia. thx in advance

**Comment by MrIvanPlays** [comment]
Whenever I can look at this issue

**Comment by MrIvanPlays** [comment]
Test with https://github.com/YatopiaMC/Yatopia/commit/78c24fde6d4e24f25e45714043428cf58c4283d1 
I wasn't able to reproduce cuz I wasn't able to make the hopper face the minecart.

**Comment by metabrixkt** [comment]
@MrIvanPlays click right mouse button on rail minecart is placed on, it's shown in my video https://mc.epserv.ru/media/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202020-08-24%2012:31:44.mp4

UPDATE: or sorry, I didn't see commit that fixed this. Thanks

**Comment by Titaniumtown** [comment]
@epserv 
![image](https://user-images.githubusercontent.com/11786225/91472219-21861e00-e865-11ea-9fbb-3ac0e06821c5.png)

**Comment by toinouH** [comment]
@Titaniumtown It works fine for me :)
