### ISSUE TITLE
End crystals can't be destroyed by snowballs

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#150]
**Expected behavior**
When I throw a snowball to end crystal, this end crystal explodes.

**Observed behavior**
When I throw a snowball at the end crystal, it just crashes into it.

**Steps to reproduce (if known)**
Just throw a snowball to end crystal.

**Installed plugins**
No plugins

**Version**
![image](https://user-images.githubusercontent.com/64396538/91078748-81f63f00-e65c-11ea-982f-ebbea685784d.png)

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/78c24fde6d4e24f25e45714043428cf58c4283d1
