### ISSUE TITLE
IllegalArgumentException Entering nether portal

### ISSUE THREAD

**Issue by ishland** [tr7zw/YAPFA#151]
**Expected behavior**
Enter the nether normally

**Observed behavior**
Enter the nether and kicked the player and crash the server.

**Steps to reproduce (if known)**
1. Enter the nether portal
2. Server kicked the player
3. Server crash

**Installed plugins**
```
Plugins (22): Barrels, BiomeIDFix, CS-CoreLib, JukeBox, MinecraftSP, MineTinker, MultiverseteBlockAPI, PlaceholderAPI, PluginManager*, ProtocolLib, QQMinecraft*, SandtoQuartz, ServerMSPT, Slimefun, sleManager*, Vault, ViaBackwards, ViaVersion, WorldEdit, XPConomy
```

**Version**
```
This server is running Yatopia version git-Yatopia-"e1a085d" (MC: 1.16.2) (Implementing API1.16.2-R0.1-SNAPSHOT)
```

**Additional context**
Server log: https://paste.ubuntu.com/p/vP7VS2r9mN/

**Comment by Titaniumtown** [comment]
Wasn't the BiomeIDFix stuff added into yatopia? Correct me if I'm wrong.

**Comment by ishland** [comment]
Everything commented here should be related to the issue. Please go to discord to talk about this.

**Comment by Titaniumtown** [comment]
wdym? I was just thinking that BiomeIDFix could be conflicting with yatopia or something :shrug:

**Comment by ishland** [comment]
This doesn't conflicts with Yatopia and it works fine for me. This was integrated into Yatopia but removed later.

**Comment by Titaniumtown** [comment]
Oh ok, thanks for the clarification.

**Comment by Titaniumtown** [comment]
I'm thinking this is a plugin issue. hmmm

**Comment by ishland** [comment]
Cannot get reproduced again since i crashed my server for about 15 times. It appears to be random

**Comment by MrIvanPlays** [comment]
Cannot reproduce on both e1a085d and 78c24fd

**Comment by ishland** [comment]
Also cannot get reproduced for me but it is purely random

**Comment by MrIvanPlays** [comment]
closing due to cannot reproduce repeatedly.
