### ISSUE TITLE
Raid do not Spawn

### ISSUE THREAD

**Issue by pr1kol-zz** [tr7zw/YAPFA#152]
**Expected behavior**
Create Raid in Village through Bad Omen

**Observed behavior**
I have Bad Omen, and I came to Village, but Raid don't Spawn, and Bad Omen does not disappear

**Steps to reproduce (if known)**
1) Accumulate the Bad Omen effect
2) Come to the Village
3) Raid don't Spawn

**Installed plugins**
Checked without plugins

**Version**
- https://imgur.com/KcruSVL

**Proof**
- https://imgur.com/4EYwNJc

**Comment by MrIvanPlays** [comment]
can you reproduce upstream?

**Comment by pr1kol-zz** [comment]
what is upstream ?

**Comment by MrIvanPlays** [comment]
Can you reproduce with paper? 
(close was accidental)

**Comment by pr1kol-zz** [comment]
Yes I can

**Comment by MrIvanPlays** [comment]
Then open a bug report there.

**Comment by pr1kol-zz** [comment]
I entered the same world, but with paper, and the raid worked.
- https://imgur.com/vzi7Cqa

**Comment by MrIvanPlays** [comment]
ok looks like there's a language barrier here. "reproduce" means does it not work there too.

**Comment by MrIvanPlays** [comment]
Could you try with latest commit and "use-block-distance-in-portal-search-radius" disabled? 
idk what's rly wrong here so im trying to guess

**Comment by pr1kol-zz** [comment]
This don't work
- https://imgur.com/BapAfa0
- https://imgur.com/yyikWgF
- https://imgur.com/Id0eock

**Comment by James76931** [comment]
Can confirm. I'm getting this issue too.

**Comment by Alexander3a** [comment]
I have the same problem

**Comment by MrIvanPlays** [comment]
I have found the source of the problem. Expect a fix soon

**Comment by MrIvanPlays** [comment]
Apparently I can't find a fix so anyone willing to help join our discord @ https://discord.io/YatopiaMC

**Comment by MrIvanPlays** [comment]
So what we've discovered so far:
seems like there's a POI data loss somewhere , its probably the cause of #185 too
