### ISSUE TITLE
Mobs have no collision with cauldrons

### ISSUE THREAD

**Issue by ItsDed** [tr7zw/YAPFA#153]
**Expected behavior**
Mobs interact with cauldron block. ie: get stuck inside, walk around etc

**Observed behavior**
Mobs completely ignore cauldron and clip through/fall through the bottom when suspended in the air.

**Steps to reproduce (if known)**
Place a cauldron with nothing below, spawn a zombie inside.
Place a cauldron on the ground, spawn a zombie inside.

**Installed plugins**
https://i.gyazo.com/5428b673339d1892c1e5a751493a11a7.png

**Version**
>....=>.... [17:50:37 INFO]: This server is running Yatopia version git-Yatopia-"78c24fd" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Additional context**
I updated my server about an hour ago and just ran into this issue. Most iron farms on the server use zombies in cauldrons, so I know it was working fine before. Going from purpur to Yatopia is the only change that was made from no issue > issue.

**Comment by MrIvanPlays** [comment]
more collision issues!

**Comment by ItsDed** [comment]
And I just had a player mention that hoppers aren't pulling items out of regular chests.

Tested and confirmed.

**Comment by Titaniumtown** [comment]
> more collision issues!

yay :upside_down_face:

**Comment by MrIvanPlays** [comment]
> And I just had a player mention that hoppers aren't pulling items out of regular chests.
> 
> Tested and confirmed.

we already have a report about minecarts, have to check about that too.

**Comment by toinouH** [comment]
Can you join the discord it would be easier to talk there: https://discord.io/YatopiaMC ? @ItsDed

**Comment by MrIvanPlays** [comment]
![image](https://img.mrivanplays.com/javaw_9ajK6YjCRB.png)
your config?
