### ISSUE TITLE
EpicWorldGenerator and Yatopia Funkyness

### ISSUE THREAD

**Issue by nagasiminecraft** [tr7zw/YAPFA#159]
[crash-2020-08-26_12.03.22-server.txt](https://github.com/YatopiaMC/Yatopia/files/5134023/crash-2020-08-26_12.03.22-server.txt)
[2020-08-26-1.log](https://github.com/YatopiaMC/Yatopia/files/5134024/2020-08-26-1.log)

Server crashing always when using Yatopia latest, i tried using Paper instead and no crash happened

**Comment by duplexsystem** [comment]
Please follow the proper issues template.

**Comment by nagasiminecraft** [comment]
**Expected behavior**
Server would run without crash with Yatopia, as i tried paper its not crash the server
**Observed behavior**
Server always crash suddenly when world is generating, i tried without player when pregen with Chunky same issue happened. The server crash stuck at saving overworld
**Installed plugins**
![Plugin](https://user-images.githubusercontent.com/34377372/91383899-de757c00-e85f-11ea-922d-7722a2b162c0.PNG)
**Version**
![image](https://user-images.githubusercontent.com/34377372/91384041-3f9d4f80-e860-11ea-8b22-3f513c430f73.png)
Tried with latest version same issue
**Additional context**
[crash-2020-08-26_12.03.22-server.txt](https://github.com/YatopiaMC/Yatopia/files/5134043/crash-2020-08-26_12.03.22-server.txt)
[2020-08-26-1.log](https://github.com/YatopiaMC/Yatopia/files/5134046/2020-08-26-1.log)

**Comment by MrIvanPlays** [comment]
Pastebin of the crash: https://pastebin.com/SpPhinNv

**Comment by MrIvanPlays** [comment]
Ok I have 0 idea of how it is working on paper but doesn't work here. MinecraftInternalPlugin was introduced by paper ![image](https://img.mrivanplays.com/idea64_HS1Bga4dw8.png)

**Comment by nagasiminecraft** [comment]
I dont know much about them,but its a fact, i already running eWG with paper 15 hours with 80 player without crash

**Comment by MrIvanPlays** [comment]
ok so apparently they're using the internal plugin to schedule tasks in order to hide that they're a bad plugin.

```
[12:03:22] [Server thread/ERROR]: Task #754660 for Minecraft v1.0 generated an exception
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_16_R2.generator.e.<init>(it.unimi.dsi.fastutil.objects.ObjectListIterator)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_16_R2.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.e(ThreadedMailbox.java:90) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.a(ThreadedMailbox.java:137) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.run(ThreadedMailbox.java:102) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_16_R2.generator.e.<init>(it.unimi.dsi.fastutil.objects.ObjectListIterator)'
	at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_16_R2.generator.f.k(lia:8) ~[?:?]
	at com.minelazz.epicworldgenerator.nativeAPI.implementations.v1_16_R2.generator.t.buildNoise(cea:445) ~[?:?]
	at net.minecraft.server.v1_16_R2.ChunkStatus.lambda$static$5(ChunkStatus.java:52) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.ChunkStatus$d.doWork(ChunkStatus.java:249) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.ChunkStatus.a(ChunkStatus.java:193) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$b$38(PlayerChunkMap.java:1261) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$b$40(PlayerChunkMap.java:1259) ~[patched_1.16.2.jar:git-Yatopia-"467f3ee"]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 8 more
```
"Minecraft 1.0" should've said "EpicWorldGenerator" but they're trying to hide their plugin so you don't blame them.
This is not a yatopia/tuinity/paper/spigot/bukkit issue. The crash is caused due to paper firing an event, nms tasks are NEVER expected to throw exceptions, however the developer didn't choose to use the proper api in place, but got inside nms to break stuff. 

The funny thing is that you claim is working fine on paper. That shouldn't be the case as NONE of the code here is touched by us.

**Comment by JakeNijssen** [comment]
Funny enough, the decision to hack NMS is competely rational. As the bukkit api support for it is quite lacking. So don’t complain about us using NMS allot of devs use NMS to get their stuff together.

**Comment by MrIvanPlays** [comment]
> Funny enough, the decision to hack NMS is competely rational. As the bukkit api support for it is quite lacking. So don’t complain about us using NMS allot of devs use NMS to get their stuff together.

yes it is understandable that you go to nms (the plugin is about chunk generation), however what is not understandable is you using the internal plugin to schedule tasks. The internal plugin has 99% of the methods implemented throwing UnsupportedOperationException, leading the server to crash due to a fault in the task. What's funny is that people claim the plugin works on paper, but none of the code is touched by us nor tuinity and people claim it doesn't work on yatopia.
What you're trying to hide? The plugin being trash?

**Comment by MrIvanPlays** [comment]
@YourPalJake so I ran your plugin thru a deobfuscator and guess what: ITS NOT OUR ISSUE.

See these 2 screenshots:
![image1](https://img.mrivanplays.com/javaw_vN631TCG9g.png)
![image2](https://img.mrivanplays.com/idea64_0jldy4EhPh.png)

Basically paper added the fastutil library to api, which was previously relocated by craftbukkit (image 2) as it was not in the api. The plugin does not handle that paper removed the relocation (image 1), resulting in this error: https://github.com/YatopiaMC/Yatopia/issues/159#issuecomment-681507445

So go ahead and fix your trash plugin. I can show you git blame on screenshot No. 2 so you don't say "It was made by you but you put Paper there"

**Comment by JakeNijssen** [comment]
Oh man, you just broke terms of agreement. You're not allowed to deobfuscate the jar.

**Comment by MrIvanPlays** [comment]
> Oh man, you just broke terms of agreement. You're not allowed to deobfuscate the jar.

OH I BROKE TERMS OF AGREEMENT :(((((((((((
Now what you're going to sue me?!?!? NO PLEASE NO IM GOING TO CRY :((((((((((((
I didn't give you a cent btw

**Comment by YourPalJake** [comment]
Even better, you used an cracked illegal copy. Oh man you have no right at all to call us "trash". When you download stuff from sites like BlackSpigot you're one of the biggest scum in this community. Shame on you, shame

**Comment by MrIvanPlays** [comment]
I didn't download it from blackspigot. a folk which downloaded the plugin legally gave it to me so we can expose your god damn trash plugin.

**Comment by YourPalJake** [comment]
That means the access of the user to the plugin can be revoked. You just screwed over someone. Its not allowed under any circumstances to redistribute the plugin. And that user did

**Comment by MrIvanPlays** [comment]
no one will tell you who was so the access of anyone wouldn't be revoked. :))))))
is a win-win situation, I expose, people start hating u, u fix, then we both win :)))))

**Comment by YourPalJake** [comment]
Though the issue is. Its an EWG error thus its logged in sentry, so I basically just have to cross reference the error and I get the userid

**Comment by MrIvanPlays** [comment]
the plugin wasn't run, only decompiled 
and the one who gave me the plugin wasn't the one reporting the issue :)))

**Comment by CocoTheOwner** [comment]
XD

**Comment by MrIvanPlays** [comment]
anyways im locking this, enough shit

**Comment by duplexsystem** [comment]
Ok first off I use this plugin so I'm going to try to fix this. Second off I apologise for @MrIvanPlays behavior. Third off your terms of agreement on Spigot lead to a 404 so you should probably fix that.

**Comment by duplexsystem** [comment]
I'm unlocking this but keep it civil.

**Comment by duplexsystem** [comment]
Ok so apparently my Github won't let me unlock the issue so I'll do that later.

**Comment by MrIvanPlays** [comment]
Update: we're not fixing it, ideas of @budgidiere wouldn't work in the real world.

For future people: this is a plugin issue and I mentioned why and what should be looked at. Apparently the plugin maintainers don't care about everything other than paper and spigot, so don't expect much from the plugin or them. The bad reviews already tell what a plugin this is.

**Comment by duplexsystem** [comment]
Hi @YourPalJake @CocoTheOwner I'm willing to work with you guys to make this work. From what I've been made aware the problem is that fact that you guys check for paper but we are not reporting as paper so EWG doesn't do the proper stuff as we are a fork of paper. Is there a way we/you can change something to fix this?

**Comment by yannicklamprecht** [comment]
EWG isn't even using the WorldGenerator "registry" right. Has no Multiverse support at least how it's done normally by passing the generator name to the MV create command. It's cool that the world is so special but if the author doesn't implement common mechanisms it is worthless.

**Comment by svdgoor** [comment]
MyWorlds works just fine. Multiverse hasn't been updated since late 2019... I don't know why someone would use such outdated software.

> EWG isn't even using the WorldGenerator "registry" right. Has no Multiverse support at least how it's done normally by passing the generator name to the MV create command. It's cool that the world is so special but if the author doesn't implement common mechanisms it is worthless.

**Comment by MrIvanPlays** [comment]
people are still using multiverse cuz it works and that it proved to be the best one throughout the years, from that the plugin is popular. some plugins does not need updating for version support if they're properly utilising the bukkit api which is meant to be forward compatible.

**Comment by DucksLock** [comment]
> MyWorlds works just fine. Multiverse hasn't been updated since late 2019... I don't know why someone would use such outdated software.
> 
> > EWG isn't even using the WorldGenerator "registry" right. Has no Multiverse support at least how it's done normally by passing the generator name to the MV create command. It's cool that the world is so special but if the author doesn't implement common mechanisms it is worthless.

https://github.com/Multiverse/Multiverse-Core just leaving this here :)
