### ISSUE TITLE
Removed player achievements 2.0

### ISSUE THREAD

**Issue by TheFaser** [tr7zw/YAPFA#164]
**Observed behavior**
All player achievements are removed. In one of the versions of iatopia, this was corrected. Then it was less common, but achievements are still disappearing

**Steps to reproduce (if known)**
This happens due to poor internet connection of the player or rebooting from another location. Possibly also due to a quick simple player restart в
[!image](https://cdn.discordapp.com/attachments/630016185462816769/748895892085669958/unknown.png)

**Installed plugins**
Happens on vanilla server

**Version**
[!image](https://cdn.discordapp.com/attachments/630016185462816769/748899353384452186/unknown.png)

**Additional context**
It's completely random and very difficult to reproduce. But this happens often on the server, among players with poor connections

**Comment by Titaniumtown** [comment]
This has happened to me as well.

**Comment by MrIvanPlays** [comment]
after the first fix we noticed that too but proxi refused to fix that due to the fact logging in from another location is already being handled hacky so this issue won’t be resolved.

**Comment by ishland** [comment]
Maybe add an option to enforce single session? Or reconnection throttle time?

**Comment by toinouH** [comment]
https://github.com/Proximyst/Rainforest/issues/3 I put that here.

@ishland If you can fix it you that's welcome 🥇

**Comment by agoniaprivat** [comment]
This happens to me aswell.

**Comment by P-333** [comment]
Me too
