### ISSUE TITLE
Hoppers don't pickup fast-moving items

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#176]
**Expected behavior**
When item fastly moves above the hopper, hopper picks it up.

**Observed behavior**
When item fastly moves above the hopper, hopper doesn't pick it up, item moves on.

**Steps to reproduce (if known)**
![image](https://user-images.githubusercontent.com/64396538/91640921-7cbd3980-ea3a-11ea-9693-66b3e64be0d9.png)

**Installed plugins**
No plugins.

**Version**
![image](https://user-images.githubusercontent.com/64396538/91640944-9f4f5280-ea3a-11ea-93b2-1cc12fe8e010.png)

**Comment by metabrixkt** [comment]
why is it marked _vanilla_ while it's yatopia bug?

**Comment by ishland** [comment]
it is a vanilla issue but gets more serious in yatopia.

**Comment by MrIvanPlays** [comment]
Seems like the "it gets more serious" comes from empty hopper ticking. Ill do more testing tommorrow.

**Comment by nkomarn** [comment]
Fixed in f18a93c22320c7d5cfd2c93d8b5dd55bbfd32a66. This was a result of the Empirecraft (EMC) hopper patch causing hoppers to only attempt to suck in items every second. Vanilla behavior has been restored, and items seem to land in the first hopper every single time.
