### ISSUE TITLE
Having issues with EpicWorldGenerator? READ ME

### ISSUE THREAD

**Issue by MrIvanPlays** [tr7zw/YAPFA#181]
THIS IS NOT A YATOPIA ISSUE ! THIS IS A PLUGIN ISSUE.

Although it is a very simple fix whilst looking at the code, the maintainers of the plugin rejected to fix compatibility. It isn't even worth it to use this plugin as seen from the reviews. If you didn't buy the plugin, then don't buy it, it is a waste of money.

THIS IS NOT A YATOPIA ISSUE ! THIS IS A PLUGIN ISSUE.

**Comment by MrIvanPlays** [comment]
more proof this plugin is garbage/waste of money
![image](https://img.mrivanplays.com/msedge_kJBtnqetZ8.png)

**Comment by toinouH** [comment]
https://www.spigotmc.org/resources/epicworldgenerator-1-15-1-16-3-%E2%9D%97%EF%B8%8Fsale-%E2%9D%97%EF%B8%8F-20-off.8067/update?update=367866
