### ISSUE TITLE
Villagers ignore doors when in a hurry

### ISSUE THREAD

**Issue by MrIvanPlays** [tr7zw/YAPFA#185]
**Expected behavior**
Villagers to open doors

**Observed behavior**
Villagers do not open doors if they're chased by zombies or whatever. Only open if they're close to them.

**Steps to reproduce (if known)**
spawn some zombies around a village

**Installed plugins**
none

**Version**
any 1.16.2 version

**Comment by duplexsystem** [comment]
Is this still an issue?

**Comment by MrIvanPlays** [comment]
with my option it kinda isnt but vanilla is still broken

**Comment by MrIvanPlays** [comment]
Needs investigation if it happens on latest too.

**Comment by MrIvanPlays** [comment]
still confirmed being an issue

**Comment by MrIvanPlays** [comment]
no longer an issue
