### ISSUE TITLE
HolographicDisplays incompatibility

### ISSUE THREAD

**Issue by illumeleet** [tr7zw/YAPFA#189]
**Expected behavior**
Everything works well

**Observed behavior**
Chunks containing HolographicDisplays holograms cannot be saved
![image](https://user-images.githubusercontent.com/51333325/92331193-861f5500-f07d-11ea-9f47-77f7ca8d4a63.png)

**Steps to reproduce (if known)**
Join server, load chunks with holograms in them and logout

**Installed plugins**
HolographicDisplays, LuckPerms, PlugMan, Vault

**Version**
![image](https://user-images.githubusercontent.com/51333325/92331157-39d41500-f07d-11ea-84f6-05a243a2c016.png)

**Additional context**
Was also tested with paper-185, there's no problems at all. So this is yatopia issue
HolographicDisplays version: v2.4.5-SNAPSHOT-b157

**Comment by MrIvanPlays** [comment]
not our issue. holographicdisplays is not using the api in place

**Comment by SoSeDiK** [comment]
I had the same issue multiple times without HolographicDisplays.

**Comment by MrIvanPlays** [comment]
Fixed in latest build.
apparently not a plugin issue
