### ISSUE TITLE
Portals disconnect after restart

### ISSUE THREAD

**Issue by TheFaser** [tr7zw/YAPFA#190]
**Expected behavior**
Portals will work fine and won't break

**Observed behavior**
The portals work fine, but after restarting the server, the portals are disconnected and new ones are created

**Steps to reproduce (if known)**
Turn off the server, turn on and go to the portal
I made it on video https://www.youtube.com/watch?v=Mvsv0X2XaDQ&feature=youtu.be

**Installed plugins**
[image](https://media.discordapp.net/attachments/652923435512758276/753233972548599828/unknown.png)

**Version**
[image](https://cdn.discordapp.com/attachments/652923435512758276/753234358499934350/unknown.png)

**Comment by toinouH** [comment]
We are aware of the bug.

**Comment by MrIvanPlays** [comment]
![image1](https://img.mrivanplays.com/msedge_9P9VncPLY0.png)
![image2](https://img.mrivanplays.com/msedge_DLXuY2ZFMm.png)
update

**Comment by MrIvanPlays** [comment]
oops, looks like im blind, ignore the reply up

**Comment by MrIvanPlays** [comment]
838aa2b should help

**Comment by MrIvanPlays** [comment]
Cannot reproduce on 1.16.3

**Comment by MrIvanPlays** [comment]
one more note, I have 0 plugins and I restarted the server manually.

**Comment by TheFaser** [comment]
This also happens on 1.16.3

**Comment by MrIvanPlays** [comment]
try reproducing without plugins & restarting your server with stop & start and not an external plugin.

**Comment by TheFaser** [comment]
First I checked it on a clean server, with plugins and without, the portals are working fine. After removing all plugins on a regular server and launching them, the portals began to work normally. I downloaded the plugins and the portals are working fine again, but this error probably only appears over time. Very strange bug)

**Comment by toinouH** [comment]
How large your world is I mean for the storage ?
How many portals do you have ? (You can estimate)

**Comment by MrIvanPlays** [comment]
so it happens with plugins. then this is either an issue with your restart plugin or a plugin which is listening to PortalCreateEvent.

**Comment by toinouH** [comment]
@TheFaser Come to discord, I'll try to help you :)
