### ISSUE TITLE
Armor stands do not collide with hoppers

### ISSUE THREAD

**Issue by MrIvanPlays** [tr7zw/YAPFA#193]
A workaround until a proper fix is found: 
in paper.yml change : armor-stands-tick to false, armor-stands-do-collision-entity-lookups to true

**Comment by toinouH** [comment]
![](https://cdn.discordapp.com/attachments/748481491008225351/754035125276115013/2020-09-11_19.40.34.png)
![](https://cdn.discordapp.com/attachments/748481491008225351/754035120876421131/2020-09-11_19.41.34.png)

**Comment by MrIvanPlays** [comment]
39b28b0
