### ISSUE TITLE
link to the last successful build in the codemc

### ISSUE THREAD

**Issue by dalandis** [tr7zw/YAPFA#201]
**Describe what do you want us to implement**

Please add a link to the last successful build in the codemc.
To make this link permanent and the latest build can be downloaded without problems with a script. 
This is done, for example, by the paper, which makes it possible to update the kernel without problems upon server restart.

**Comment by toinouH** [comment]
You can use the command ```
?1.16.3``` in #botspam of our discord server.
But I have a gift for you:
https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%252F1.16.3/lastSuccessfulBuild/

**Comment by dalandis** [comment]
This is not quite right
Example script for paper

```
as_user "wget -q -O $MCPATH/paper.jar.update https://papermc.io/ci/job/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar"
        if [ -r "$MCPATH/paper.jar.update" ]
        then
                if ! diff $MCPATH/$CB_JAR $MCPATH/paper.jar.update >/dev/null
                then
                        echo "update"
                        as_user "mv $MCPATH/paper.jar.update $MCPATH/$CB_JAR"
                else
                        echo "not update"
                        as_user "rm $MCPATH/paper.jar.update"
                fi
        fi
```
Your link changes for each build. Today is https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%252F1.16.3/lastSuccessfulBuild/artifact/target/yatopia-1.16.3-paperclip-b20.jar
And for example tomorrow https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/ver%252F1.16.3/lastSuccessfulBuild/artifact/target/yatopia-1.16.3-paperclip-b21.jar

**Comment by MrIvanPlays** [comment]
https://api.yatopia.net/v2/latestBuild/download?branch=ver/1.16.3

we had that api for a while ^ you could just join our discord to see the announcements.

**Comment by dalandis** [comment]
> https://api.yatopia.net/v2/latestBuild/download?branch=ver/1.16.3
> 
> we had that api for a while ^ you could just join our discord to see the announcements.

Thanks, this looks like the right thing.
I joined the discord a week ago but haven't seen this API.

Thanks and sorry for distracting.
