### ISSUE TITLE
Hoglins don't run away from warped fungus

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#202]
**Expected behavior**
You place warped fungus next to hoglin, and right after this or in 1 second, hoglin runs away from the warped fungus.

**Observed behavior**
You place warped fungus next to hoglin, and hoglin doesn't run away from the warped fungus.

**Steps to reproduce (if known)**
1. Place warped fungus next to hoglin.
2. Hoglin should run away from it. (but it doesn't)

**Installed plugins**
No plugins.

**Version**
git-Yatopia-"af38251", 1.16.3, downloaded from codemc

**Additional context**

**Comment by MrIvanPlays** [comment]
cannot reproduce on latest 1.16.3

**Comment by duplexsystem** [comment]
Is this still an issue?

**Comment by toinouH** [comment]
I did not test recently but I had it.

**Comment by MrIvanPlays** [comment]
yes it is
