### ISSUE TITLE
Ticking Player and IllegalArgumentException: Cannot Get Property BlockStateEnum Crashes Server Upon Entering Nether

### ISSUE THREAD

**Issue by Justsnoopy30** [tr7zw/YAPFA#205]
**Expected behavior**
Player to be able to enter the nether successfully.

**Observed behavior**
The server crashes.
Error: https://paste.gg/p/anonymous/befff22835cc41e6a4c39584f2c30324

**Steps to reproduce (if known)**
1. Install Incendium Nether Datapack
2. Generate and have players enter the nether
3. Observe crash.

**Installed plugins**
Plugins (23): AngelChest, BadlionClientModAPI*, BetterEnd, CMI, CMIPaperLib, CoreProtect, DiscordSRV,  (WorldEdit)FastAsy
ncWorldEdit, JukeBox, LagAssist, LuckPerms, MyCommand, NoteBlockAPI, PlaceholderAPI, PlayerParticles, PluginManager*, ProtocolLib, RandomTeleport, Spartan, Votifier, VotingPlugin, WorldGuard, WorldGuardExtraFlags

**Version**
git-Yatopia-f2a29e3 (MC: 1.16.3)

**Additional context**

**Comment by MrIvanPlays** [comment]
do you have `use-block-distance-in-portal-search-radius` enabled?

**Comment by MrIvanPlays** [comment]
> Install Incendium Nether Datapack

wait nvm, not our issue

**Comment by Justsnoopy30** [comment]
It is Yatopia's issue... it's not a plugin. It's a datapack and seems to work properly on Vanilla, Bukkit, Spigot, Paper, and Tuinity, and breaking on Yatopia.

**Comment by MrIvanPlays** [comment]
working properly without plugins / datapacks? yes.
not our issue then

**Comment by duplexsystem** [comment]
jfc ivan stop. If it's a plugin/datapack issue that breaks with us it's still our problem the only time it wouldn't be is a NMS plugin.

**Comment by Justsnoopy30** [comment]
What I'm thinking is that some code in Yatopia expects a certain blockstate (Direction or Axis State) to exist in a certain nether block it is expecting (perhaps basalt), but instead it finds a red sand without the blockstate, generated by the datapack.

**Comment by MrIvanPlays** [comment]
the code where this exception is thrown is not modified by us. @budgidiere 
there is only a stream replacement by akarin which is vastly improved by me which fixes yet another issue with portals.

**Comment by Justsnoopy30** [comment]
Tested fixed.
