### ISSUE TITLE
Entities fall through Hoppers, Slabs, and Stairs

### ISSUE THREAD

**Issue by Saraistupid** [tr7zw/YAPFA#212]
**Expected behavior**
 
Entities to not fall through Hoppers, Slabs, and Stairs
**Observed behavior**

Entities fall through Hoppers, Slabs, and Stairs
**Steps to reproduce (if known)**

1: Place a stair, slab, or hopper
2: Summon a mob on it (or let one fall to it)
3: Observe.
**Installed plugins**

`Plugins (16): AsyncWorldEdit, AsyncWorldEditBossBar, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, floodgate-bukkit, Geyser-Spigot, LuckPerms, Pingas*, SpigotPing, UltimateStacker, Vault, ViaBackwards, ViaVersion, WorldEdit`
**Version**

`This server is running Yatopia version git-Yatopia-"6c04ab5" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Previous version: git-Yatopia-"1af2160" (MC: 1.16.3)
You are running the latest version`

**Timings**

https://timings.aikar.co/?id=181e93c3f5254ffdaf4aaa000e5d74ad

**Comment by metabrixkt** [comment]
Same issue, also toinouH saw this on my screen share in the VC in discord

**Comment by duplexsystem** [comment]
I've personally verified this is an issue on my own testing. I know what patch it is. @MrIvanPlays If we can't fix the issues we need to remove the collision opts patch
