### ISSUE TITLE
Horses jump near to fences, trying to escape

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#216]
**Expected behavior**
As you can see in the attached video, the horses are able to exit the fence gate in an anomalous way.
Video URL: https://youtu.be/xOzW3pBADUU

**Installed plugins**
https://gyazo.com/78cfe6ffaadcbce033c73d5e0c77d29e

**Version**
https://gyazo.com/f1a49bbc46a91937f81f10940ff38a46

**Comment by MrIvanPlays** [comment]
I made some changes recently with entity collisions _yet again_ so try reproducing on latest

**Comment by MrIvanPlays** [comment]
confirmed to be an issue, but they just jump next to a fence gate and cant come out of them.

**Comment by NovaPixell** [comment]
exactly

**Comment by MrIvanPlays** [comment]
Since they don't get out this is getting moved in a low priority 
If you can find a fix then we advice you to pr.

**Comment by MrIvanPlays** [comment]
so this is what happens: they think fences are 1 block tall, and they try to jump over them. i still think its something with collisions, and here's my theory of what happens in code: horses think its a normal block, but then lithium's optimization finds that there are fences in this chunk, fences are oversized blocks so it gives another shape, but horses have memorised them as non-oversized blocks and desperately try to get out.

**Comment by MrIvanPlays** [comment]
no longer an issue
