### ISSUE TITLE
Same problem, the server crashes...

### ISSUE THREAD

**Issue by iSilviu-debug** [tr7zw/YAPFA#218]
**Expected behavior // Observed behavior**
I rewrite the same problem as the recently closed post. When the server loads blocks in Async that are deleted with a plugin or simply the load of deleted blocks, the server crashes with 20 tps and 0.8 ticks.

**Steps to reproduce (if known)**
Load of blocks that are placed / eliminated in async

**Installed plugins**
Plugins (67): AntiAutoCannon*, AntiCooldown, AutoBroadcast, BlowableObsidians, BuycraftX, CannonFix*, ChatControl, ChorusFruit, CMI, CMIEInjector*, CMIPaperLib, CombatLogX, ConditionalCommands*, CoreProtect, CrazyAuctions, Drycell, Envoys, Factions, FactionsRoster*, FactionsTop, FactionsTopv5Hologram, FastAsyncWorldEdit, FeatherBoard*, FishRodFix, FogusCore, GoldenCrates, HolographicDisplays, HolographicExtension, InventorySaver, ItemSoulBind, LuckPerms, mcMMO, MVdWPlaceholderAPI*, Netherportals, NoBedExplosions, Nobreakspawner, NoCheatPlus, NotchAppleCrafter*, ObsidianBreaker, Outpost*, PlaceholderAPI, PlugMan, PrinterMode, PvPLevels, SAML, Scyther, ServerNPC, ServerTutorialPlus*, ShopGUIPlus, SimplePortals, spark, SpigotGuard, SSX-Connector*, TAB, TerraformGenerator, TNTFill*, TokenManager, UltraRegions, Vault, VoidGenerator, WildApi, WildBuster, WildStacker, WildTools, WorldBorder, WorldEdit, WorldGuard

**Version**
This server is running Yatopia version git-Yatopia-"0faeed7" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Timings**
//
**Error*
https://pastebin.com/9kVA5Vs8

**Additional context**
😢 😿

**Comment by Titaniumtown** [comment]
Could you provide timings? you just sent a pastebin link lol.

**Comment by MrIvanPlays** [comment]
> Could you provide timings? you just sent a pastebin link lol.

we dont need timings this isnt a performance issue

**Comment by duplexsystem** [comment]
> we dont need timings this isnt a performance issue

it's useful for config and more info about plugins.

**Comment by Titaniumtown** [comment]
> it's useful for config and more info about plugins.

Yea, that's what I was thinking.

**Comment by iSilviu-debug** [comment]
Server just started with timings:
https://timings.aikar.co/?id=a2200f7fdfff44edbef19a77ba162821

Although it's not a performance issue:
https://spark.lucko.me/#Pa3nmzDa1f

**Comment by iSilviu-debug** [comment]
I tried now to place 9 chunks on paper and I noticed that after 600 times the server crashes; same error
I tried with WildBuster, to mine the chunks, what is the plugin?

**Comment by ghost** [comment]
There was a issue with this related on Tuinity, i believe leaf reverted it today. Try again on Tuinity latest build and see if it solves it.

**Comment by MrIvanPlays** [comment]
Tuinity fixed a completely different issue. Please if you dont have anything useful to add dont comment.

**Comment by iSilviu-debug** [comment]
However I tried and it doesn't work D:

**Comment by MrIvanPlays** [comment]
I've made a fix we're going to test if everything's fine.

**Comment by iSilviu-debug** [comment]
Ok I'll wait thanks

**Comment by duplexsystem** [comment]
@iSilviu-debug We have a fix we are testing. If you want to try it: https://github.com/YatopiaMC/Yatopia/pull/219
but please don't put it on production. It is a test build.

**Comment by iSilviu-debug** [comment]
Ok now I try it, thanks anyway

**Comment by iSilviu-debug** [comment]
Oh perfect! it is fixed it does not crash though when I use WildBuster and I put a lot of them where they start working together and I go far enough I have a really big lag

https://timings.aikar.co/?id=7795fcc3c76c4262ba9b8f95432b5410#timings

**Comment by iSilviu-debug** [comment]
I understand that there are so many, but in the timings the plguin is not marked even so much

**Comment by MrIvanPlays** [comment]
it is causing a lot of block updates after all so its not something easily fixable. 
the only possible way as of now to fix this is to make the developer of the plugin either slow it down or add an option for how slow the removal process should be.

**Comment by iSilviu-debug** [comment]
Ok no problem, it was just to see if the server crashed. Thanks a lot again for everything: D
