### ISSUE TITLE
Totally broken nether generation

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#226]
**Expected behavior**
Server generates world without any broken chunks.

**Observed behavior**
While chunk generation in the nether (I didn't see this issue in overworld) server sometimes generates random blocks, etc. (idk how to explain it)

**Steps to reproduce (if known)**
1. Start the server and let it generate the spawn area.
2. Build nether portal, activate it and enter the nether.
3. Look around.

Example: my random seed is -7790113514419973154, coordinates 31.60 103.42 -31.57 (about 50 blocks from the nether portal)

**Installed plugins**
No plugins.

**Version**
[14:40:09 INFO]: This server is running Yatopia version git-Yatopia-"0b9ce71" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[14:40:09 INFO]: Checking version, please wait...
[14:40:10 INFO]: Previous version: git-Yatopia-"e0e01cf" (MC: 1.16.3)
[14:40:10 INFO]: You are running the latest version

**Timings**
I don't have them because of "Please wait at least 3 minutes before generating a Timings report. Unlike Timings v1, v2 benefits from longer timings and is not as useful with short timings. (81 seconds)"

**Additional context**
I think this issue must be **high priority**, it's really annoying and game breaking.

**Comment by MrIvanPlays** [comment]
can u provide a video? i cba to generate the world

**Comment by nkomarn** [comment]
Confirmed to exist on the latest build. We'll be looking heavily into this.

**Comment by metabrixkt** [comment]
Video if needed https://youtu.be/DMqsRIUL7XU
