### ISSUE TITLE
Add ... Printer ?!

### ISSUE THREAD

**Issue by iSilviu-debug** [tr7zw/YAPFA#229]
**Describe what do you want us to implement**
Wondering if a lot is possible, add the PRINTER for faction games in 1.16.3. Seeing as minecraft removed this block building feature in versions after 1.8, I would ask if it is possible to add this awesome method! Thanks a lot!!

**Is your feature request related to a problem**
Let's say, it's a packet limit issue affecting the player after he gets past many placed blocks (packetblockplace)

**Additional context**
🌵

**Comment by MrIvanPlays** [comment]
I dont understand. Explain for residence players

**Comment by iSilviu-debug** [comment]
Printer: https://www.youtube.com/watch?v=UUWkS34L7io&ab_channel=m0dest

The printer would be an automatic build of a minecraft client to build Cannons or other structures (farm etc.) faster.
The problem is that when blocks are built in very fast mode, the server does not calculate the packets sent by the player and cancels them leaving space blocks.

**Comment by MrIvanPlays** [comment]
clientside problem then. not something we are capable of fixing or porting to another version.
