### ISSUE TITLE
Can't shear mooshrooms

### ISSUE THREAD

**Issue by Hellohi3654** [tr7zw/YAPFA#234]
**Expected behavior**
 
When using shears on a mooshroom they drop red mushrooms and turn into a normal cow
**Observed behavior**

Shearing sound is played but nothing happens
**Steps to reproduce (if known)**

Spawn mooshroom attempt to shear
**Installed plugins**

![image](https://user-images.githubusercontent.com/57390764/95027226-a543ed80-06e2-11eb-95cf-427f8a8f4669.png)
**Version**

![image](https://user-images.githubusercontent.com/57390764/95027232-affe8280-06e2-11eb-9d26-b03e6896a0b9.png)
**Timings**

https://timings.aikar.co/?id=51877fca02304deca2939736d56a160f
**Additional context**

**Comment by nkomarn** [comment]
I tested on build 90 (latest stable build, what you appear you be running) and I had no such issue. Try checking to make sure it's not a plugin issue.

**Comment by MrIvanPlays** [comment]
Cannot reproduce on latest ( non considered stable ) . Make sure you're in survival mode, creative doesn't work.

**Comment by MrIvanPlays** [comment]
closing due to numerous people unable to reproduce.
