### ISSUE TITLE
ModelEngine plugin spamming error when using Yatopia

### ISSUE THREAD

**Issue by ArtifactyNight** [tr7zw/YAPFA#240]
**Expected behavior**
no error spamming

**Observed behavior**
Console Spamming when i just spawned a mob with ModelEngine.
i already tested on paper server so it's work fine

**Steps to reproduce (if known)**
• spawning mythicmob with modelengine model

**Installed plugins**
![](https://i.imgur.com/kLsgWL6.png)

**Version**
![](https://i.imgur.com/J8iWK4v.png)

**Additional context**
Spamming Logs: https://pastebin.com/EeKh3yiD
Mythicmob file: https://pastebin.com/Jj09sN5S
Model Engine: https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-entity-model-manager-1-14-1-16-3.79477/

**Comment by MrIvanPlays** [comment]
Its a plugin issue, that's caused by us. I contacted the dev and we will see how it will turn.

**Comment by MrIvanPlays** [comment]
![image](https://img.mrivanplays.com/DiscordCanary_0w0y4NExPs.png)
