### ISSUE TITLE
Kick disconnects do not respect modified leave messages

### ISSUE THREAD

**Issue by nkomarn** [tr7zw/YAPFA#243]
**Expected behavior**
When a user is kicked using /kick, the custom leave message defined in Essentials displays.

**Observed behavior**
The default Minecraft message displays instead of the modified message.

**Steps to reproduce (if known)**
Install Essentials. Modify the leave message in config.yml. Kick a user using /kick. Observe the bug.

**Version**
Build 90 with async tracker.

**Additional context**
![image](https://user-images.githubusercontent.com/22900187/95126145-d6d0af00-070a-11eb-9595-6e247ac638e1.png)

I am creating this issue so I can track the fix.

**Comment by metabrixkt** [comment]
Same issue. Also I think this message is in code, because I have Russian locale on both client and server (replaced **assets/minecraft/lang/en_us.json** by russian locale) sides, but I get English message.

**Comment by MrIvanPlays** [comment]
I know why and ill fix it l8r today
