### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#247]
**Expected behavior**
Server shouldn't crash randomly

**Observed behavior**
Server does crash A LOT, relevant part of the log: https://pastebin.com/nH5vqhpN

**Steps to reproduce (if known)**
Just have the server sit there and it crashes randomly.

**Installed plugins**
![Screenshot from 2020-10-08 13-02-31](https://user-images.githubusercontent.com/11786225/95490778-b309a500-0966-11eb-9404-7d30bb278de6.png)

**Version**
![Screenshot from 2020-10-08 13-02-49](https://user-images.githubusercontent.com/11786225/95490762-adac5a80-0966-11eb-8dbb-3c7b03fbc47a.png)

This is CONSTANT it's so annoying, I have to end up killing the server and starting it again. Sometimes it's only after 5 minutes of it being up, sometimes hours. Seems pretty random in timing.

**Comment by MrIvanPlays** [comment]
These crashes occur because of GC being overloaded with objects. we're investigating into this issue currently

**Comment by Titaniumtown** [comment]
@MrIvanPlays Oh ok. Thank you! Hope this can be resolved soon! It's really a pain having to constantly restart the server. Since you mentioned GC, I'm using Aikar's flags, would using different GC flags fix the issue? I want to better understand what a possible temp fix would be (if there is one).

**Comment by MrIvanPlays** [comment]
actually the crash you provided looks more like you have a lot of network traffic going on, which is delaying the controlled packet flush. so you should try reproducing this on different hardware and different network.

**Comment by Titaniumtown** [comment]
@MrIvanPlays Hmm that is interesting. Thanks for the tip. I'll comment if I find any temporary fix.

**Comment by MrIvanPlays** [comment]
if the server crashes at like more than 24 hours its definitely GC being overloaded leading it to a out of memory crash, but the behavior you describe me is unknown to me actually...

**Comment by Titaniumtown** [comment]
@MrIvanPlays I'm restarting the physical server right now (not just the minecraft sever, but the machine). :crossed_fingers: this is a last ditch effort.

**Comment by Titaniumtown** [comment]
It hasn't crashed yet, I'll keep you posted.

**Comment by Titaniumtown** [comment]
Update: Crashed again. Would the java version be an issue? I'm using openjdk 15.

**Comment by MrIvanPlays** [comment]
try reproducing without plugins

**Comment by Titaniumtown** [comment]
@MrIvanPlays good idea! I'm doing that right now.

**Comment by Titaniumtown** [comment]
Very interesting, With just ViaVersion and ViaBackwards, no crash. I'm going to start adding the plugins back until something breaks.

**Comment by NDevTK** [comment]
I think I get the same issue there is also references to protocollib.

**Comment by NovaPixell** [comment]
This morning I had this crash with similar errors. Then I would tell you that the problem is ProtocolLib! Anyone report to them?

**Comment by NDevTK** [comment]
I dont think its a ProtocolLib bug as it was working fine on paper.
