### ISSUE TITLE
Projectiles lag

### ISSUE THREAD

**Issue by Ytoblo** [tr7zw/YAPFA#249]
Snowball Lagging

when a snowball passes through the nether portal, server's tps falls sharply, and when you just throw it, it also falls, but not much

![image](https://user-images.githubusercontent.com/45790049/95662018-5c11f480-0b4d-11eb-88a6-c050fb96a95f.png)

**Comment by Titaniumtown** [comment]
Can you share a link to your timings? Not just a picture lol.

**Comment by nkomarn** [comment]
Throwing snowballs through a Nether portal causes similar lag on Tuinity. Also, please elaborate on "when you just throw it, it also falls, but not much" if possible. Thanks!

**Comment by MrIvanPlays** [comment]
thru a nether portal - vanilla issue
despawn rates have been fixed recently so update to latest and see what will happen with just throwing it

**Comment by MrIvanPlays** [comment]
putting in low prio - anyone willing to pr the fix will be appreciated too.

**Comment by metabrixkt** [comment]
I'd rename it to Projectile Lag, because
> when a snowball passes through the nether portal, server's tps falls sharply

it also happens with egg, arrows, etc

**Comment by MrIvanPlays** [comment]
#287 improves the situation a little bit. If it is a single projectile there won't be a big problem, with it you need to spam projectiles in order to lag the server.

**Comment by MrIvanPlays** [comment]
@Ytoblo was it fixed?
