### ISSUE TITLE
Idea for build server

### ISSUE THREAD

**Issue by gavinft** [tr7zw/YAPFA#25]
I have a recommendation here. If you don’t want to host a build server like Jenkins, you could try using GitHub actions. They can run after each commit (if you set them up that way) and you use docker files to make them build whatever you want. I could try to make a PR later today with GitHub actions.

**Comment by gavinft** [comment]
Bruh I’m stupid you already have it setup

**Comment by Obydux** [comment]
Yes

**Comment by tr7zw** [comment]
Currently, the goto is the Github Actions, but there is the codemc Jenkins building it too(and deploying it to maven), but it currently builds only master, not the two mainly used branches. https://ci.codemc.io/job/Tr7zw/job/YAPFA/
