### ISSUE TITLE
"time set ___" resets day counter to 0

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#250]
**Expected behavior**
/time set ___ should bump the day 1 and change the time to the requested one

**Observed behavior**
/time set ___ resets the day counter to 0 and then changes that time of day

**Steps to reproduce (if known)**
use /time set

**Installed plugins**
![image](https://user-images.githubusercontent.com/11786225/95670263-ed399900-0b56-11eb-851d-c0b213599b23.png)

**Version**
![image](https://user-images.githubusercontent.com/11786225/95670268-f75b9780-0b56-11eb-940a-aeffe44b1afe.png)

**Comment by metabrixkt** [comment]
This behavior is ok, as far as I know.

**Comment by metabrixkt** [comment]
Tested, it happens of vanilla.

**Comment by MrIvanPlays** [comment]
Purpur has recently added a patch to configure the daylight cycle and idk if it helps with it.

Maybe you could test on purpur and see if it works properly, if it does we'll port [that](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.3/patches/server/0135-Configurable-daylight-cycle.patch) patch and close the issue.

**Comment by metabrixkt** [comment]
@MrIvanPlays since @Titaniumtown doesn't reply, I can test it today if needed.

And will this patch affect Bukkit API methods behavior?

**Comment by greysilly7** [comment]
It shouldnt affect the bukkit api

**Comment by MrIvanPlays** [comment]
after further investigation, `/time set`'s behavior is to _set_ the time to the specified time amount, not to bump day 1.
