### ISSUE TITLE
Blazes from spawners have no AI and don't attack the player

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#252]
**Expected behavior**
Blazes that spawn in nether fortresses (from spawners) should have AI and attack the player

**Observed behavior**
Blazes that spawn in nether fortresses (from spawners) don't have any AI and don't attack the player.

**Version**
![image](https://user-images.githubusercontent.com/11786225/95690037-f1ab9380-0be2-11eb-8568-2e1416081e86.png)

**Additional context**
Blazes that spawn not from spawners (naturally) in fortresses have AI

**Comment by nkomarn** [comment]
Do you by chance have `nerf-spawner-mobs` enabled in the Spigot config?

**Comment by Titaniumtown** [comment]
Yes, that is set to true. should I disable it in order for the blazes to function properly?
