### ISSUE TITLE
Directly 20 TPS constant

### ISSUE THREAD

**Issue by Euphillya** [tr7zw/YAPFA#255]
**Describe what do you want us to implement**
Modify Bukkit.getTPS()[0] to 20* constant

**Comment by ghost** [comment]
if (server_name.equals("Yatopia")){
  this.tps = 20;
}

**Comment by MrIvanPlays** [comment]
haha ur so funny ~~/s~~
thanks for contributing to the already messy github issue history

**Comment by NessieMate** [comment]
if (server_lag)){
dont;
}
