### ISSUE TITLE
Dysfunctional functions and a snow golem that does not spawn snow

### ISSUE THREAD

**Issue by ghost** [tr7zw/YAPFA#256]
Observed behavior
1. Guys, the snow golem doesn't make snow when it moves!
![image](https://user-images.githubusercontent.com/71688822/96346571-1ef5b700-10a5-11eb-9351-3b472d48ed18.png)
2. purpur.yml

```
blocks:
    barrel:
      six-rows: true  #The function is enabled but does not work in the game!
```
![image](https://user-images.githubusercontent.com/71688822/96346619-6b40f700-10a5-11eb-9078-746bf99cba95.png)

```
     ender_chest:
      six-rows: true
      use-permissions-for-rows: false #The function is enabled but does not work in the game!
```
![image](https://user-images.githubusercontent.com/71688822/96346641-91ff2d80-10a5-11eb-80dc-8e21b93858ce.png)

Installed plugins
![image](https://user-images.githubusercontent.com/71688822/96346558-0b4a5080-10a5-11eb-9de3-ea7d9dc690b1.png)

Version
![image](https://user-images.githubusercontent.com/71688822/96346561-14d3b880-10a5-11eb-907f-d761a21beb5a.png)

**Additional context**

**Comment by ishland** [comment]
Please follow the issue template correctly and open a separate issue for purpur things
