### ISSUE TITLE
Issue with purpur patch for 6 row enderchests: "Packet processing error"

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#258]
**Expected behavior**
When "six-rows" is set to true in purpur.yml for enderchests, enderchests should have 6 rows

**Observed behavior**
You set "six-rows" to true in purpur.yml for enderchests, when a player opens an enderchest, it kicks them with the error: "Packet processing error"

**Steps to reproduce (if known)**
Open an enderchest with "six-rows" enabled for enderchests in purpur.yml

**Installed plugins**
![image](https://user-images.githubusercontent.com/11786225/96389735-1e315380-117f-11eb-8f4d-cef85b8f78a0.png)

**Version**
![image](https://user-images.githubusercontent.com/11786225/96389742-28ebe880-117f-11eb-9e62-c7a0ce75eb6b.png)

**Comment by MrIvanPlays** [comment]
Cannot reproduce. 
If I have to guess its either floodgate or geyser being funky _yet again_

**Comment by MrIvanPlays** [comment]
Closing as "cannot reproduce" and no response.
