### ISSUE TITLE
Support luckperms with bungeecord

### ISSUE THREAD

**Issue by Fulburger** [tr7zw/YAPFA#279]
Actually when using Bungeecord (or waterfall fork) with luckperm on this and on yatopia server , player cannot join this (work correctly with Paper)

Screenshot who hapen : 
![image](https://user-images.githubusercontent.com/58354967/98108007-9ac07380-1e9b-11eb-8943-4cc3972d74c6.png)

**Comment by MrIvanPlays** [comment]
properly set bungee online mode in paper.yml

**Comment by Fulburger** [comment]
It work ! i don't know why with paper it work without :/
