### ISSUE TITLE
Nether Portal (Final fix?)

### ISSUE THREAD

**Issue by iSilviu-debug** [tr7zw/YAPFA#284]
**Expected behavior || Observed behavior || Steps to reproduce (if known)** 
I have long noticed that the Nether portals, when used, lagging behind. This consists of two parts: creating and teleporting.
This fact is perhaps possible to fix. I noticed that the portals have a 
```
                            e.getSearchRadius();
                            e.getCreationRadius();
```
Are not Async and so create a little Spike Lag on the ticks.
I tried to set them with the event:
```
                            e.setSearchRadius(0);
                            e.setSearchRadius(0);
```
and the tick increment has not risen because it does not find portals around it.
I only ask if it is possible to ASYNC on these methods above all to create a portal that teleports, creates blocks and searches for portals in ASYNC.

**Installed plugins**
*in TIMINGS*

**Version**
[18:18:53 INFO]: This server is running Yatopia version git-Yatopia-"24b5188" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Timings**
These timings are very wrong as I was trying a plugin that fixes portals with async chunks:
https://timings.aikar.co/?id=49907784ece5459e822775fa7b1b3502

**Additional context**
🌵

**Comment by iSilviu-debug** [comment]
New timings without plugins that affect the use of the portal:
https://timings.aikar.co/?id=e577ec349afc4d49ad29ee75a4d337aa

**Comment by toinouH** [comment]
Could you try to send projectiles in the nether portal ? We know it does some lag (especially with snowballs) ?

**Comment by iSilviu-debug** [comment]
ok no problem

**Comment by iSilviu-debug** [comment]
These timings are rehearsed with a snowball thrown into a portal:
https://timings.aikar.co/?id=18f0942fe09549c382a65534995f68c7

I tried two ways, one way was to throw the ball on the top, _**blue surface**_, and it made it float; then I tried to throw the snowballs at the bottom, _**red surface**_, and it didn't lagging.
![Immagine 2020-11-13 184336](https://user-images.githubusercontent.com/67197594/99103644-2d6dba80-25e0-11eb-8fff-cf8757b18bee.png)

**Comment by toinouH** [comment]
As I can see on timings snowballs are still unhappy :c

**Comment by iSilviu-debug** [comment]
ah, ok .. because of the player?
I can test snowballs using a plugin that takes away the vanilla minecraft portal radius, for fun

**Comment by iSilviu-debug** [comment]
Same thing, the snowballs are unhappy .. for the fact that before, the blocks behind the portal were the problem, so the snowballs didn't go inside.

**Comment by MrIvanPlays** [comment]
Thanks for the work done by you. Perfect idea, but not really sure if we can realise it. Making a pull request will be appreciated
