### ISSUE TITLE
Problem with ice blocks

### ISSUE THREAD

**Issue by iSilviu-debug** [tr7zw/YAPFA#288]
**Expected behavior**
The ice should melt without lagging.

**Observed behavior**
The main problem is BlockFadeEvent, the event that melts ice or other minecraft blocks. This as I noticed goes up by 100 ticks on Spark.

**Steps to reproduce (if known)**
Melt a block like ice

**Installed plugins**
 Plugins (63): **AdvancedEnchantments**, AntiAutoCannon*, BlowableObsidians, ChatControl, ChorusFruit, CMI, CMIEInjector*, CMIPaperLib, CollectorsX, CombatLogX, ConditionalCommands*, CoreProtect, CrazyAuctions, DeluxeTags*, Drycell, Factions, **FactionsTop**, **FactionsTopv5Hologram**, (WorldEdit)FastAsyncWorldEdit, FeatherBoard*, FishRodFix, FogusCore, GenBucket, GoldenCrates, HolographicDisplays, ItemSoulBind, LibsDisguises, LuckPerms, ManageFactions, MVdWPlaceholderAPI*, NoBedExplosions, NoCheatPlus, NoMobAI, NotchAppleCrafter*, OldCombatMechanics, Outpost*, PetMaster, PlaceholderAPI, PlugMan, PrinterMode, ProtocolLib, SAML, Scyther, ServerNPC, ServerTutorialPlus*, ShopGUIPlus, spark, SpigotGuard, SSX-Connector*, TAB, TerraformGenerator, TNTFill*, TokenManager, UltraRegions, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, **WildStacker**, WildTools, WorldBorder, WorldGuard

**Version**
[20:02:56 INFO]: This server is running Yatopia version git-Yatopia-"596b1b7" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[20:02:56 INFO]: Previous version: git-Yatopia-"6d0288b" (MC: 1.16.4)
Same Both versions

**Timings**
_I have no timings because I fixed it by temporarily disabling the event._

**Additional context**
🌵 @MrIvanPlays it is very nice ^^

**Comment by Titaniumtown** [comment]
> Ice cream

lol

**Comment by MrIvanPlays** [comment]
why event lag plz fix

```java
        CraftBlockState state = CraftBlockState.getBlockState(world, pos);
        state.setData(newBlock);
```

unfortunately nothing much we can do here

**Comment by iSilviu-debug** [comment]
got it, not even a block placed in async?

**Comment by MrIvanPlays** [comment]
i like how ure being super optimistic about async stuff but its not just like "make it async" its a hell more complicated than that 
I can make the event not call if there are no listeners, I highly doubt tho there would be a change.

**Comment by iSilviu-debug** [comment]
okay i understand too that i program only plugins and small programs which is very difficult, i also had some ideas with generating chunks, how to melt the ice in the chunks where the player is. It would also be a nice idea to generate chunks differently. For example, if you spread out in one point, do not generate 16x16 blocks x 256 of height, therefore in total 65,536 blocks, but in a particular way how to generate half a chunk and half blocks of height and depth. If it could be done it's hell but it's very nice, at least for me, the idea.

**Comment by MrIvanPlays** [comment]
I'd like to see timings of this otherwise im closing as wontfix

**Comment by iSilviu-debug** [comment]
sure

**Comment by Titaniumtown** [comment]
lmao "Ice cream" is still in the title

**Comment by iSilviu-debug** [comment]
funny way to name an issue right? haha

**Comment by toinouH** [comment]
I'll clean this issue, you can still talk on Discord

**Comment by MrIvanPlays** [comment]
no timings provided - closing as wontfix
