### ISSUE TITLE
Server crashes all day

### ISSUE THREAD

**Issue by RavenskyPaul** [tr7zw/YAPFA#290]
I don't know what to write but, it all crashes after 30minutes all day

Here the logs
https://pastebin.com/sTM0U32e

Timings before crash:
https://timings.aikar.co/?id=a2271761135847f48ca3bb708b97621c#timings

**Comment by MrIvanPlays** [comment]
update.

**Comment by toinouH** [comment]
It was on the latest and I asked to use an older to test and as you can see it's the same issue.

**Comment by toinouH** [comment]
https://timings.aikar.co/?id=ea7239a50f144af980177fb124e1ffac#timings
