### ISSUE TITLE
Purpur features won't work

### ISSUE THREAD

**Issue by Corenb** [tr7zw/YAPFA#291]
**Observed behavior**
Purpur features like edit or colored signs, placeable minecart or minable spawner with silktouch.

**Steps to reproduce (if known)**
Enable these features in purpur.yml config file.

**Version**
MC1.16.4 | git-Yatopia-"74bcf06"

**Comment by MrIvanPlays** [comment]
you can't just add the config options in purpur.yml and expect them to work. 
its not how it works mr. wandering smith

if you want anything ported let us know in a new issue.

**Comment by Corenb** [comment]
Ok sorry, I thought they worked as they are presents in the [PATCHES.md](https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.4/PATCHES.md) file and patches subdirectories.
For your information, I don't add it myself to my purpur.yml file, they was by default as I use Purpur before Yatopia.

So I gonna open new issue for each feature.
