### ISSUE TITLE
Crashes crashes..

### ISSUE THREAD

**Issue by 0VERR** [tr7zw/YAPFA#294]
Hi yatopia crashing my server for a few builds, crash logs: https://pastebin.com/wPDmh3VR

**Comment by MrIvanPlays** [comment]
1. follow the issue template
2. --- DO NOT REPORT THIS TO YATOPIA - THIS IS NOT A BUG OR A CRASH  - git-Yatopia-"a47bfa7" (MC: 1.16.4) ---

your server got overloaded

**Comment by 0VERR** [comment]
My specs: GAME-2 - AMD Ryzen 7 3800X - 64GB DDR4 ECC 2666MHz - 2x SSD NVMe 960GB Enterprise Class Soft RAID, 

In addition, there were only about 100 players back then, where up to 140 can stay on 20 tps without any problems

Other fork works well, i dont know why, only with yatopia my server crashes :/

I have a second server on which I also use yatopi, and nothing like that happens there, here on yatopia crashes every 30 minutes: /
