### ISSUE TITLE
Feature Request: Tuinity's starlight

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#295]
**Describe what do you want us to implement**
Could you implement Tuinity's starlight? It gives AMAZING performance with the lighting engine, thanks!

**Comment by MrIvanPlays** [comment]
whenever leaf considers it stable enough to be in the master branch of tuinity ; thats when we will have starlight.
this is the final decision. making any requests won't make a difference.

**Comment by MrIvanPlays** [comment]
https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/leaflight%252Fver%252F1.16.4/

**Comment by Titaniumtown** [comment]
this issue can be closed because starlight is now in the master branch of tuinity
