### ISSUE TITLE
Feature request : Edit and color sign Purpur features

### ISSUE THREAD

**Issue by Corenb** [tr7zw/YAPFA#296]
**Describe what do you want us to implement**
Could you implement edit and color sign feature from Purpur patches ? They are easy to use with their Purpur permissions and we don't need to install others plugins to do it.

**Comment by ghost** [comment]
Not performance related, we here at yatopia only support performance. Please close this.

**Comment by Corenb** [comment]
> 
> 
> Not performance related, we here at yatopia only support performance. Please close this.

![image](https://user-images.githubusercontent.com/1338450/100100295-e47bf880-2e60-11eb-92ee-98eb07dc0ead.png)
🧐

**Comment by ghost** [comment]
![22222](https://user-images.githubusercontent.com/60317441/100106661-198c4900-2e69-11eb-8f82-224c767c1246.PNG)

He must have forgotten to remove it 😂

**Comment by MrIvanPlays** [comment]
when I am on pc I will port them. 
@Alejandro-Sosa if they’re easy to maintain why not

**Comment by ghost** [comment]
Since you changed your mind. While your at it please pull flying squids aswell.

**Comment by MrIvanPlays** [comment]
i haven't _fully_ changed my mind. editable signs and colors in signs make sense.
flying squids don't. so flying squids is no.

**Comment by MrIvanPlays** [comment]
ok i fucked up the issue but ya there you go
https://github.com/YatopiaMC/Yatopia/commit/23b9e93f399767a114eab22ca882b4f31811f3f6
