### ISSUE TITLE
Api to stable update for easy update

### ISSUE THREAD

**Issue by Gontier-Julien** [tr7zw/YAPFA#303]
**Describe what do you want us to implement**
An api like the development build but for stable build for easy update to latest stable build

For example : https://api.yatopia.net/v2/latestStable/download?branch=ver/1.16.4

**Comment by Gontier-Julien** [comment]
Any news ?

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/api.yatopiamc.org/commit/462d64cafe9172204df9628f839eadaa659463e9
