### ISSUE TITLE
Coral fix | Tnt dupe machine

### ISSUE THREAD

**Issue by TofaToP** [tr7zw/YAPFA#304]
Hello, I have a question

Karall disappears on the tnt machine, apparently yatopia is fixing this dup, how can I disable this fix?

Plugins: 
plugin list: ChatEx*, ChestCommands, CoreProtect, DiscordSRV, Essentials, IllegalStack, LuckPerms, NitroCommandBlocker*, PL-Hide, PlaceholderAPI, Plan, PosePlugin, ProtocolLib, SkinsRestorer, TAB, Vault, WhitelistPro*, WorldEdit

ILEGALSTACK CFG: https://hastebin.com/lubihejexi.yaml

**Comment by Titaniumtown** [comment]
This is a fix by paper, not Yatopia. There are config options in paper.yml to disable or enable it.

**Comment by Titaniumtown** [comment]
> Karall

?

**Comment by TofaToP** [comment]
> > Karall
> 
> ?

coral* sorry, i'm from Russia

**Comment by TofaToP** [comment]
> This is a fix by paper, not Yatopia. There are config options in paper.yml to disable or enable it.


what is the name of this setting in paper.yml?

**Comment by MrIvanPlays** [comment]
paper explicitly didnt add options to disable the fixes. and we won't too.

**Comment by Titaniumtown** [comment]
Yes they did?

**Comment by TofaToP** [comment]
> paper explicitly didnt add options to disable the fixes. and we won't too.


So how do I disable the fix? : D

**Comment by Titaniumtown** [comment]
In paper.yml, the section called "unsupported-settings"
