### ISSUE TITLE
Server crushed

### ISSUE THREAD

**Issue by pipexxx** [tr7zw/YAPFA#309]
**Expected behavior**

 Stable server work

**Observed behavior**

Server crushed

**Steps to reproduce (if known)**

The server is frozen. No errors or warnings appeared in the log and console. After 2 hours, the server issued the following error: https://pastebin.com/CqHg2vNu

**Installed plugins**

This: https://imgur.com/a/nLvHpXA

**Version**
 
git-Yatopia-"a47bfa7" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Timings**

Server crushed. 

**Additional context**

I'm almost 100% sure it was a malicious attack

**Comment by MrIvanPlays** [comment]
thread starvation caused this. the thread starvation is caused by luckperms trying to connect to a sql type database. not a yatopia issue
