### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by msmanui** [tr7zw/YAPFA#310]
Basically, i did run the version #5 of https://ci.codemc.io/job/YatopiaMC/job/Yatopia/job/leaflight%252Fver%252F1.16.4/.

I tried this one because i had some  park unsafe in the SPARKS so duplex told me that that was fixed https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.4/patches/server/0051-Improve-task-performance.patch

I started the server and after 25-30 mins the server crash with this error:

[message (10).txt](https://github.com/YatopiaMC/Yatopia/files/5646745/message.10.txt)

**Comment by ishland** [comment]
Please follow our issue template 
This issue is caused by a plugin, not that patch

**Comment by msmanui** [comment]
> Please follow our issue template
> This issue is caused by a plugin, not that patch

I dont have any crashes, this is the first crash i've of this kind. I use purpur. 

List of plugins:
https://i.gyazo.com/e1b7927e000867fee831bfa23a18f49a.png

**Comment by MrIvanPlays** [comment]
server got overloaded while protocollib was trying to inject something.
we need more details so we can help you.

**Comment by andris155** [comment]
Maybe the Marriage Master plugin is causing this.

**Comment by MrIvanPlays** [comment]
Fixed some time ago by https://github.com/YatopiaMC/Yatopia/commit/d072a3583aa1c5bb3ac7de347134c143c47d13d0
another person had the same issue and after we made the changes in the mentioned commit it was gone.
