### ISSUE TITLE
Purpur - Crying Obsidian as Portal Frames

### ISSUE THREAD

**Issue by Skizzles** [tr7zw/YAPFA#312]
**Describe what do you want us to implement**

I would like the ability to use Crying Obsidian as portal frames as it was suggested by my player base.
**Is your feature request related to a problem**

Not really, just seems the purpur addition is not present in yatopia.
**Additional context**

I believe this would be nice to be added as it gives a use to crying obsidian for members of servers, it also does not do any harm as much as I can tell, gives good design to portals.

**Comment by MrIvanPlays** [comment]
crying obsidian already has its use. it is nonsensical to make portals off crying obsidian, cuz its - well - crying obsidian. you can't set water on fire in the real world, can you? I'd like to stick with mojang's decisions for such stuff.
