### ISSUE TITLE
Loading of chunks cause TPS drops

### ISSUE THREAD

**Issue by TheDevTec** [tr7zw/YAPFA#317]
**Expected behavior**
The server lags behind when loading chunks

**Observed behavior**
When players load blocks or join the world in an unloaded chunk (And chunks are very very slowly loading), the TPS server quickly drops to 7 TPS

**Steps to reproduce (if known)**
---

**Installed plugins**
https://i.imgur.com/G3hXFfx.png

**Version**
https://i.imgur.com/kANCBL5.png

**Timings**
https://timings.aikar.co/?id=8881f5d8692749e0ae4c8862130e888d

**Comment by MrIvanPlays** [comment]
hmm i wonder why 
![image](https://img.mrivanplays.com/msedge_QYCCp57nkV.png)

**Comment by TheDevTec** [comment]
So simply change the value of Xms to 12288M?

**Comment by MrIvanPlays** [comment]
yes

**Comment by TheDevTec** [comment]
https://timings.aikar.co/?id=df2dc094e40f4472b6bf5ade089811c0

EDIT. TPS fluctuate between 17 and 20
And sometimes I must wait around 3s to load chunk

EDIT2: After some loading of chunks with players (10 - 20 TPS)
https://timings.aikar.co/?id=3ea83b0b4a664e86a862f973519146dd

**Comment by toinouH** [comment]
You should join our Discord to get a better support. :)

**Comment by MrIvanPlays** [comment]
what's your hardware

**Comment by TheDevTec** [comment]
I7 8700 (available for our server is 5 threads)
12gb ram

**Comment by MrIvanPlays** [comment]
configurations aren't optimised at all. 
i7 8700 doesn't have the best single core performance.
im pretty sure you're mistaken with cores, but if that's true, 5 threads means that the jvm is limited by hell a lot. 

this is not yatopia related issue.
