### ISSUE TITLE
Implement missing Purpur patches for ender dragon gameplay behavior adjustment.

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#318]
**Describe what do you want us to implement**
Implement Purpur's gameplay modification patches for ender dragon to always drop egg and full experience. This gives purpose and reason to actually respawn the ender dragon for other players to fight it instead of nothing being provided.

https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0045-Ender-dragon-always-drop-egg.patch
https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0046-Ender-dragon-always-drop-full-exp.patch

**Is your feature request related to a problem**
No, unless missing Purpur patches is a problem?

**Additional context**
Yatopia has other Purpur patches that allow modifying gameplay and mob behavior. It however seems to be missing quite a few from upstream Purpur. While perhaps some may not make sense to add, please consider re-adding some of the simpler patches for gameplay feature adjustment.

Yatopia generated purpur.yml
https://paste.gg/p/anonymous/81e297b3312c47799f06359699507f7e/files/1ce0ee195c4a4c50bf50f9e4dc86f646/raw

Purpur generated purpur.yml
https://paste.gg/p/anonymous/5a594e41f18a48ce8e7c6b392438ab4b/files/d73077a8600842668b2d61ed6120305d/raw

**Comment by MrIvanPlays** [comment]
https://tenor.com/8pOE.gif

**Comment by mibby** [comment]
Why not?
