### ISSUE TITLE
Sponges disappear when placing more than 1

### ISSUE THREAD

**Issue by Hellohi3654** [tr7zw/YAPFA#320]
**Expected behavior**
 
When places more than one sponge all of them don't disappear
**Observed behavior**

When placing a sponge with more than one in a stack it removes all the other sponges so your left with only one sponge
It happens with wet and dry sponges
**Steps to reproduce (if known)**

Get a stack of sponges place one down and the other 63 disappear
(Works with both wet and dry sponges)
**Installed plugins**

![image](https://user-images.githubusercontent.com/57390764/102711694-b5499180-430f-11eb-9faf-7888b824a4ce.png)

**Version**

![image](https://user-images.githubusercontent.com/57390764/102711703-c1355380-430f-11eb-91ce-6b2cb451b2df.png)

**Timings**

https://timings.aikar.co/?id=c4d8400c2c4b43b296ac0866f129f36e
**Additional context**

**Comment by Hellohi3654** [comment]
Also what's this?
![image](https://user-images.githubusercontent.com/57390764/102711741-15403800-4310-11eb-8592-7adc334c9dcd.png)
Why was it privated or deleted

**Comment by metabrixkt** [comment]
Probably plugin issue. I can't reproduce this.

**Comment by Hellohi3654** [comment]
maybe if I update

**Comment by Hellohi3654** [comment]
4 versions behind

**Comment by toinouH** [comment]
> Also what's this?
> ![image](https://user-images.githubusercontent.com/57390764/102711741-15403800-4310-11eb-8592-7adc334c9dcd.png)
> Why was it privated or deleted

This is more a joke than anything else.

You should update all your plugins too.

**Comment by Hellohi3654** [comment]
Lol did it work at all?

**Comment by toinouH** [comment]
> Lol did it work at all?

As it is offtopic I can share you some screen of the code on discord 👍

**Comment by Hellohi3654** [comment]
I'm guessing it was entirely a joke

**Comment by Hellohi3654** [comment]
> > Lol did it work at all?
> 
> As it is offtopic I can share you some screen of the code on discord 👍

Yes please
