### ISSUE TITLE
translation request

### ISSUE THREAD

**Issue by zhishixiang** [tr7zw/YAPFA#321]
Hello ,I am a Chinese Minecraft server owner,I am very interestig in your server core and I want to translate it in Chinese and publish in a China Minecraft forum [MCBBS](https://www.mcbbs.net) .Looking for your reply,thx:)

**Comment by ahdg6** [comment]
It's a Server Software,that means it can't be translated in some ways.
If you wanna propaganda it in Chinese,I think the intention is good but I perfer [ishland](https://github.com/ishland) to do that.He is the contributor of Yatopia from China which means he has further understand of this software.

I'm not official of yatopia, these are just some of my views.
Thank you.

**Comment by MrIvanPlays** [comment]
we made a way to change the bundled translations with whatever you want, but if they're not official ones don't ask for support from us.

**Comment by toinouH** [comment]
@zhishixiang come on Discord and @epserv will tell you how it works.

**Comment by Kylepoops** [comment]
Do you mean to translate the introduction?
