### ISSUE TITLE
Return end gateways do not teleport players back to the main end island

### ISSUE THREAD

**Issue by AJMFactsheets** [tr7zw/YAPFA#322]
**Expected behavior**
Return end gateways teleport players back to the main island

**Observed behavior**
Return end gateways do not teleport players anywhere

**Steps to reproduce (if known)**
1. Go to the end dimension
2. Kill the ender dragon
3. Pearl through the end gateway that is generated
4. Try to pearl back through the end gateway

**Installed plugins**
Plugins (0):

**Version**
This server is running Yatopia version git-Yatopia-"4da7b3a" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Additional context**
I have investigated this issue and have found removing lines 77-83 in yatopia patch `0063-Tile-Entity-optimizations.patch` fixes this issue. When a player first enters an end gateway, it's return location should be stored in the `ExitPortal` field of the gateway's nbt. However, the bugged end gateways have no `ExitPortal` field at all, rendering them unable to teleport. It seems the end gateway's chunk location is incorrectly set to null. `isChunkLoaded` returns `true` yet the chunk object is still null. As a result, the gateway is skipped in the pending tile entity list, thus the change to it's `ExitPortal` field is lost.

Thanks for all the work! :+1:

**Comment by MrIvanPlays** [comment]
thanks for the information you gave me. I'm fixing this ASAP
