### ISSUE TITLE
Error in last build leaflight 

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#323]
**Observed behavior**
An error occurs in the console for some unknown reason, after which nothing can be written to the chat, and after the re-entry, the player's actions are rolled back.

**Steps to reproduce (if known)**
Is unknown

**Installed plugins**
Plugins (0):

**Version**
leaflight version git-yatopia-6a2e1ac

**Additional context**
Logs: https://pastebin.com/WBy5Z9CZ

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/0db6e9f4015cc18e801c9075a898b1913c6fd326
