### ISSUE TITLE
Again for an unknown reason the problem in leaflight

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#324]
**Observed behavior**
After the appearance of this problem in the console, some players can not write to the chat, and after re-entering the server, they are rolled back.

**Steps to reproduce (if known)**
Unknown

**Installed plugins**
Plugins (25): ArmagidonInvisibleUtils, ArmorStandTools, AuthMe, BetterBeds*, Chatty, ChristmasPresents*, ConsoleSay*, CoreProtect, CoreProtectTNT, CustomHeads*, DiscordSRV, HolographicDisplays, HolographicPlaceholders, LightChatBubbles*, MOTD, MySkin, OpenInv, PermissionsEx*, PlaceholderAPI, PlayerReport, PosePlugin, ProtocolLib, RPSystem*, TabList, Vault.

**Version**
Leaflight Yatopia last version git-Yatopia-"0db6e9f" (MC: 1.16.4)

**Additional context**
https://pastebin.com/h6Q0egGM

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/6d6bb01bb2c521168928598fb99fe2e94277533c
