### ISSUE TITLE
Port more purpur patches

### ISSUE THREAD

**Issue by krolik-exe** [tr7zw/YAPFA#325]
Could you implement these patches from purpur? 

0027-Giants-AI-settings  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0027-Giants-AI-settings.patch)

0088-Allow-color-codes-in-books  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0088-Allow-color-codes-in-books.patch)

0076-Mending-mends-most-damages-equipment-first  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0076-Mending-mends-most-damages-equipment-first.patch)

0079-Implement-elytra-settings  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0079-Implement-elytra-settings.patch)

0046-Ender-dragon-always-drop-full-exp  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0046-Ender-dragon-always-drop-full-exp.patch)

0043-Pigs-give-saddle-back  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0043-Pigs-give-saddle-back.patch)

0045-Ender-dragon-always-drop-egg  -  [LINK](https://github.com/pl3xgaming/Purpur/blob/ver/1.16.4/patches/server/0045-Ender-dragon-always-drop-egg.patch)

**Comment by mibby** [comment]
https://github.com/YatopiaMC/Yatopia/issues/318

**Comment by MrIvanPlays** [comment]
![no](https://user-images.githubusercontent.com/37958105/103175543-5639ce80-4873-11eb-8a94-d97f3026fb87.gif)

**Comment by krolik-exe** [comment]
But why?

**Comment by krolik-exe** [comment]
Could You port some patches then from purpur, that You think are ok? or add config for these patches that You're not sure about implementing them, because some of these i listed, and some, i didn't list , are very useful for us, players, and please, think about it
