### ISSUE TITLE
Update Starlight branch to Starlight 0.0.2-RC3

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#327]
Tuinity Starlight branch has received some significant updates and fixes with the release of Starlight 0.0.2-RC3. Most notably also fixing compatibility with FastAsyncWorldEdit & the ``/paper fixlight`` command.

Please consider expediting an upstream merge with Tuinity ahead of your usual merge times.
https://github.com/Spottedleaf/Tuinity/commits/dev/lighting

**Comment by MrIvanPlays** [comment]
yatopia's currently at https://github.com/Spottedleaf/Tuinity/commit/d2aa70f12401ada0cc25239afd279bfd149eae1f
fixlight is not very important thing given that starlight is baically bugproof so yea

**Comment by mibby** [comment]
Ah, I see it was silently merged in with this commit. It just wasn't in the log for new commits pulled in the bulk upstream merge. 
https://github.com/YatopiaMC/Yatopia/commit/21d5a4ea24fef7adcfec4c68addc0398bfff7d79#diff-77578ae04cec9b17e8e463736226547374bba8a5111ce30fbf1eacaef25ff705

I agree, just fixlight isn't that important to force another merge early. Thanks.
