### ISSUE TITLE
Mobs going through portal instantly despawn on the other side 

### ISSUE THREAD

**Issue by BenjaminEmag** [tr7zw/YAPFA#328]
**What is supposed to happen**
Portals are supposed to load an area around them when an entity or item goes through. 

**What's Happening*
Portals don't load an area around them when an entity or item goes through causing mobs to instantly despawn when going through portals

**Steps to reproduce (if known)**
Make a portal outside of spawn chunks and go through. Once you have two linked portals spawn a creeper inside of the portal blocks causing it to go into the nether. When you go to the nether the creeper will not be their as it was never loaded therefore instantly despawns 

**Installed plugins**
![image](https://user-images.githubusercontent.com/75389318/103395659-3fa6a800-4afd-11eb-829e-00ab9353bdfd.png)

**Version**
![image](https://user-images.githubusercontent.com/75389318/103395649-2998e780-4afd-11eb-8800-97b4495f8781.png)

**Timings**
https://timings.aikar.co/?id=2b557e7ccf8944cc979372f06a1f9224

**Additional context**
If this does exist maybe make it a configurable option rather then just doing it as this breaks portal based farms.

**Comment by MrIvanPlays** [comment]
transfer from nether to overworld works, but transfer from overworld to nether doesn't 
that's a weird bug

**Comment by MrIvanPlays** [comment]
1.16.5 fixed
