### ISSUE TITLE
Village Bug

### ISSUE THREAD

**Issue by LevM-A** [tr7zw/YAPFA#330]
**Expected behavior**
 
Villager move and update products
**Observed behavior**

Villager Doesn't move and update products
**Steps to reproduce (if known)**

I don't know how, but it happened after a build update (if I'm not mistaken)
**Installed plugins**

Plugins (34): AdvancedBan, AntiVPN, AuthMe, Chatty, CoreProtect, CoreProtectTNT, Discord2FA*, DiscordSRV, DiscordSRVUtils, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Geyser-Spigot, GSit, Hat, JustOneMore*, LeVSkins, LightChatBubbles*, LuckPerms, MegaVanish, MOTD, OpenInv, PL-Hide, PlaceholderAPI, ProtocolLib, rBookOnline, rHideTags*, rRPChat, ServerUtils, SmoothSleep, TAB, Vault, WorldBorder, WorldGuard
**Version**

[00:53:59 INFO]: This server is running Yatopia version git-Yatopia-"aaeb472" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[00:53:59 INFO]: Checking version, please wait...
[00:53:59 INFO]: Previous version: git-Yatopia-"aad302f" (MC: 1.16.4)
[00:53:59 INFO]: You are 7 version(s) behind
**Timings**

https://timings.aikar.co/?id=a134b5aac6fe404d96d4859654f00116
**Additional context**

My server is Vanila RolePlay, if you can say what plugins i need delete to fix that problem(if that is plugin bug)

**Comment by MrIvanPlays** [comment]
try reproducing on latest;
also, a few suggestions: use aikar's flags and optimise your configurations.
