### ISSUE TITLE
Bug with maps from build 33 and after

### ISSUE THREAD

**Issue by tommasobenatti** [tr7zw/YAPFA#331]
**Expected behavior**
The maps will be empty untill you take it in your hand from build 33 and after

**Observed behavior**
Basically after build 33 the maps arn't loaded untill you take one in your hand, and you you clear your inventory and rejoin the map displays empty

**Steps to reproduce (if known)**
Create a map, put it in a item frame, clear your inventory, quit and rejoin, you will see that the map is displaying empty

**Installed plugins**
essentialsx

**Version**
On build 33 and 34 there is the problem, in build 32 there isn't, so i guess is a problem of build 33

**Timings**
none

**Additional context**
I've made a 4 minutes video https://www.youtube.com/watch?v=wgFhKBQtu1s

**Comment by MrIvanPlays** [comment]
try reproducing with build №35 after it shows up on https://yatopiamc.org/download

**Comment by tommasobenatti** [comment]
With the build 35 the problem is gone
