### ISSUE TITLE
Broken item names

### ISSUE THREAD

**Issue by heraqu** [tr7zw/YAPFA#334]
Hi, I have a yatopia but I have terrible tps drops, but it doesn't matter. I want to transfer yatopia to a different server software, i.e. tuinity, when I transfer all item files at the market or store, they have a bad name. What could it be?

Latest version
![image](https://user-images.githubusercontent.com/46068203/104118623-c4c66400-532a-11eb-9984-5fb62c775170.png)
![image](https://user-images.githubusercontent.com/46068203/104118626-cb54db80-532a-11eb-909d-c236e244ecc0.png)
![image](https://user-images.githubusercontent.com/46068203/104118629-d1e35300-532a-11eb-8240-db5ea94c9607.png)

**Comment by MrIvanPlays** [comment]
we give no support if you switch the server software constantly.
next time follow the issue template.

**Comment by toinouH** [comment]
https://i.gyazo.com/5b108130e6704e2c17e08726f827f773.jpg
https://i.gyazo.com/906668d4d1f7d28751e7aabb4773e406.png
From one dedi to another but there is no story related to switching from Yatopia to Tuinity or something.
Suspected plugin zAuctionHouse.

**Comment by toinouH** [comment]
> le problème vient tout simplement du transfère du au ftp ou sftp
[21:44] GroupeZ - Support Discord #general

"The problem comes from the ftp or sftp's transfer"
