### ISSUE TITLE
Update dev/asynctracker2

### ISSUE THREAD

**Issue by Ytoblo** [tr7zw/YAPFA#336]
I want a merge 1.16.4 updates in asynctracker, like leaflight

And plz, ivan dont tell somethin like: "this branch is unstable, i dont wanna do this"

 And im apologise for my bad english

**Comment by MrIvanPlays** [comment]
1. this branch is unstable
2. this branch was meant to be merged into ver/1.16.4, but i declined, because of changes i don't approve (unstable branch)
3. the branch has not been deleted because of some of the code that's in it

it is not getting updated.
