### ISSUE TITLE
slow world generation

### ISSUE THREAD

**Issue by fulcanelly** [tr7zw/YAPFA#341]
if Yatopia forks Purpur why don't it uses Starlight world generation ?

**Comment by duplexsystem** [comment]
We've blacklisted purpur tuinity commit so only on the leaflight branch

**Comment by MrIvanPlays** [comment]
yatopia's upstream is tuinity.
starlight is not for world generation. it is a light engine rewrite.
we have a separate branch that includes starlight. you can download from our ci

next time stick to the issue format. and also, world generation in 1.16 has always been slow.
