### ISSUE TITLE
SpongePowered Mixins

### ISSUE THREAD

**Issue by ghost** [tr7zw/YAPFA#342]
**Describe what do you want us to implement**
Allow using mixins in plugins for runtime code injection. It will be amazing killer feature for plugin developers

**Comment by MrIvanPlays** [comment]
1. not possible
2. no

**Comment by ghost** [comment]
Why not?

**Comment by MrIvanPlays** [comment]
did u read 1?

**Comment by duplexsystem** [comment]
It's possible but out of scope of this project.

**Comment by ghost** [comment]
https://github.com/LXGaming/BukkitBootstrap it possible

**Comment by duplexsystem** [comment]
Yes possible but again out of scope.
