### ISSUE TITLE
Second passenger is getting teleported back when dismounting a boat

### ISSUE THREAD

**Issue by metabrixkt** [tr7zw/YAPFA#343]
**Expected behavior**
When a driver of the boat dismounts, a passenger becomes a driver.

**Observed behavior**
When a driver of the boat dismounts, a passenger gets teleported back to the location where they sat into the boat.

**Steps to reproduce (if known)**
Needs two people or accounts to test. Let's call them A and B.
1. **A** sits into the boat.
2. Then **B** sits into the boat.
3. Drive e.g. 100m (100 blocks).
4. **A** dismounts.
5. **B** got teleported back to the location when **B** sat into the boat.

**Installed plugins**
No plugins.

**Version**
1.16.5 git-Yatopia-"89d994b"

**Timings**
I guess they aren't needed this time. Happens with default configs.

**Additional context**
I'm not sure it's Yatopia bug. It have never happened on paper.

**Comment by MrTechyyy** [comment]
Unable to reproduce with `git-Yatopia-"65b2b1f" (MC: 1.16.5)`.

**Comment by metabrixkt** [comment]
@MrTechyyy I can show you this on my server tomorrow (Jan 20, around 10 am UTC)

**Comment by MrTechyyy** [comment]
@epserv I don't have time to test on your server (busy at school).
You could make a video for demo?
Also did you try switching jars with Paper/updating to latest commit

**Comment by metabrixkt** [comment]
> @epserv I don't have time to test on your server (busy at school).
> You could make a video for demo?
> Also did you try switching jars with Paper/updating to latest commit

@MrTechyyy No, I didn't. I'm not sure switching back to paper is 100% safe. Also I'm using some API yatopia adds. This bug is present since I switched to yatopia (it was August 25th I guess)

Yes I'll record a video tomorrow.

**Comment by MrIvanPlays** [comment]
>  Also I'm using some API yatopia adds. 

what are you using?

**Comment by Titaniumtown** [comment]
> Yes I'll record a video tomorrow.

He was never seen since....

**Comment by metabrixkt** [comment]
> > Yes I'll record a video tomorrow.
> 
> He was never seen since....

ill try to not forget again

**Comment by metabrixkt** [comment]
ok, I see there aren't any specific steps to reproduce, or maybe it got fixed in latest builds

**Comment by metabrixkt** [comment]
Found it! It's reproducible only if boat driver isn't server operator (probably second passenger shouldn't be operator too, but I didn't check it)

**Comment by metabrixkt** [comment]
Closing it since I didn't notice that my test server had plugins when I testing this bug, not reproducible w/o plugins, so it's plugin issue.
