### ISSUE TITLE
Building Yatopia on Windows

### ISSUE THREAD

**Issue by SoSeDiK** [tr7zw/YAPFA#348]
**Describe what do you want us to implement**
Support for building Yatopia on Windows machines.

**Is your feature request related to a problem**
Build fails during `./gradlew paperclip` step because:

java.io.IOException: Cannot run program "mvn" (in directory "C:\Users\User\Documents\GitHub\Yatopia\Paper\work\Paperclip"): CreateProcess error=2, The system cannot find the file specified

**Additional context**
The problem is in this line: https://github.com/YatopiaMC/Yatopia/blob/ver/1.16.5/buildSrc/src/main/kotlin/task/Paperclip.kt#L25
`mvn` should be `mvn.cmd` on Windows.
So would be nice to detect if the machine is running Windows and use a different command.

**Comment by Titaniumtown** [comment]
Use WSL

**Comment by duplexsystem** [comment]
Unfortunately we have never had native windows support. It's always been through git bash, a bash emulator for windows, while git bash can be used on windows to make this work it's not on the top of our priority list. Untill someone, most likely me, gets around to it I recommend using another alternative like WSL.

**Comment by Titaniumtown** [comment]
@duplexsystem since building on windows doesn't work, why not remove `gradlew.bat` until the issue is fixed?

**Comment by Titaniumtown** [comment]
@SoSeDiK can you try #381 to see if that resolves your issue?

**Comment by SoSeDiK** [comment]
Yep, that works.

**Comment by Titaniumtown** [comment]
Ok!
