### ISSUE TITLE
Slow chunks generation 

### ISSUE THREAD

**Issue by gamerover98** [tr7zw/YAPFA#358]
**Expected behaviour**

I'm the developer of a custom world generator. My plugin doesn't use **ANY** type of reflections or aggressive way to generate the world. It just uses the Bukkit API. 
I can't share its code publicly due to it's a payment plugin on Spigot.

My implementation is the async chunks generation implemented with the default **generateChunkData(World, Random, x, z, biomes)** of **ChunkGenerator** bukkit class.

The following screenshot has taken with Paper 1.16.5 (latest version) and the world generation works fine!
![correct img](https://i.imgur.com/9PuK0L5.png)

**Observed behaviour**

Yatopia doesn't throw any console warning or error.

The following screenshot has taken with the latest Yatopia server. The world chunks generation is very slow during Yatopia processing.
![slowness img](https://i.imgur.com/uw6GL6b.png)

**Steps to reproduce (if known)**
Generate the world with my plugin, the default Minecraft generation seems to work fine.

**Installed plugins**
You can see all installed plugins into the timings.

**Version**
 Yatopia version git-Yatopia-3 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Timings**
[Paper timings](https://timings.aikar.co/?id=d48e04551c0d44f79dd83c92262955a0#timings)
[Yatopia timings](https://timings.aikar.co/?id=e2ec78dd5eb9479c8da89a6617f4a0c4#timings)

**Additional context**
By watching the timings, I don't note any issue with my plugin but, one can be mistaken.

**Comment by gamerover98** [comment]
With **Build #94 (Sun Oct 04 09:10:58 UTC 2020)** my plugin works fine.
With **Build #95 (Sun Oct 04 15:25:49 UTC 2020)** it doesn't work.

This is the commit: https://github.com/YatopiaMC/Yatopia/commit/82a792e78634952ffeb7ec258f84062f1632a378

Is that who's responsible for all this?

**Comment by Titaniumtown** [comment]
Confirmed by @gamerover98 privately that #361 fixed his issue.
