### ISSUE TITLE
"no-compromises" in readme is misleading

### ISSUE THREAD

**Issue by silversquirl** [tr7zw/YAPFA#359]
This text implies there is no downside to Yatopia's performance, whereas in reality some of Yatopia's patches change vanilla mechanics, requiring very real compromises.

**Comment by Titaniumtown** [comment]
Which patches changes vanilla mechanics?

**Comment by silversquirl** [comment]
Even just base Paper changes vanilla mechanics

**Comment by duplexsystem** [comment]
I'm inclined to agree. I don't know if I wrote it but if it did I didn't think of this. I'll change the readme when I get the time.

**Comment by Pieter-Auqkwa** [comment]
Maybe something in the lines of 
Blazing fast Tuinity fork with focus on performance.

**Comment by Titaniumtown** [comment]
It's not a fork of Tuinity though.
