### ISSUE TITLE
The recipe book does not work with oraxen.

### ISSUE THREAD

**Issue by SuggarHidden** [tr7zw/YAPFA#366]
**Expected behavior**
That the recipe book works as before, this happened when I upgraded to version 1.16.5.

**Observed behavior**
It happened when I upgraded to 1.16.5, I was using 1.16.4 before.

**Steps to reproduce (if known)**
I'm using minecraft version 1.16.4 and the oraxen plugin 1.68.0

**Installed plugins**
ProtocoLib v4.6.0-SNAPSHOT-b492
Oraxen 1.68.0 (It works fine without this plugin.)

**Version**
This server is running Yatopia version git-Yatopia-14 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Tuinity-"d3ee222" (MC: 1.16.5)

**Comment by Titaniumtown** [comment]
> wiht oraxen

?

**Comment by Titaniumtown** [comment]
Can you reproduce upstream?

**Comment by SuggarHidden** [comment]
Works fine with tuinity.
Version:
This server is running Tuinity version git-Tuinity-"d3ee222" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by ishland** [comment]
Any error messages logged?

**Comment by SuggarHidden** [comment]
No, you just don't see the recipes in the recipe book, even if you have all the recipes unlocked. You can also ask the creator of oraxen for the plugin to test it for free and see the bug.

**Comment by ishland** [comment]
Recipe book seems working for me (ignore resourcepack issue)
![image](https://user-images.githubusercontent.com/30385023/105940310-f9118280-6095-11eb-9fce-4eab8dd33908.png)

**Comment by SuggarHidden** [comment]
I mean the minecraft recipe book, the green book. In survival mode.

**Comment by ishland** [comment]
Currently, you can set `Misc.reset_recipes` to false in Oraxen config. 
We are now investigating this issue.
