### ISSUE TITLE
More Purpur config options

### ISSUE THREAD

**Issue by duplexsystem** [tr7zw/YAPFA#37]
These have to be config options from purpur
include link to patch

**Comment by ghost** [comment]
My personal most important ones are `0005-Barrels-and-enderchests-6-rows` , `0112-Redstone-deactivates-spawners` , `0075-Allow-leashing-villagers`

Entity lifespan might be useful regarding performance.

0005-Barrels-and-enderchests-6-rows.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0005-Barrels-and-enderchests-6-rows.patch)

0043-Tulips-change-fox-type.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0043-Tulips-change-fox-type.patch)

0035-Giants-AI-settings.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0035-Giants-AI-settings.patch)

0036-Illusioners-AI-settings.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0036-Illusioners-AI-settings.patch)

0037-Zombie-horse-naturally-spawn.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0037-Zombie-horse-naturally-spawn.patch)

0038-Charged-creeper-naturally-spawn.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0038-Charged-creeper-naturally-spawn.patch)

0039-Rabbit-naturally-spawn-toast-and-killer.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0039-Rabbit-naturally-spawn-toast-and-killer.patch)

0049-Cows-eat-mushrooms.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0049-Cows-eat-mushrooms.patch)

0052-Snowman-drop-and-put-back-pumpkin.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0052-Snowman-drop-and-put-back-pumpkin.patch)

0057-Allow-soil-to-moisten-from-water-directly-under-it.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0057-Allow-soil-to-moisten-from-water-directly-under-it.patch)

0061-Option-to-toggle-milk-curing-bad-omen.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0061-Option-to-toggle-milk-curing-bad-omen.patch)

0074-Villagers-follow-emerald-blocks.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0074-Villagers-follow-emerald-blocks.patch)

0075-Allow-leashing-villagers.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0075-Allow-leashing-villagers.patch)

0099-Implement-respawn-anchor-explosion-options.patch - [Link](https://github.com/pl3xgaming/Purpur/tree/ver/1.16/patches/server)

0098-Implement-bed-explosion-options.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0098-Implement-bed-explosion-options.patch)

0104-Entity-lifespan.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0104-Entity-lifespan.patch)

0112-Redstone-deactivates-spawners.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0112-Redstone-deactivates-spawners.patch)

0031-MC-4-Fix-Item-position-desync.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0031-MC-4-Fix-Item-position-desync.patch)

0044-Breedable-Polar-Bears.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0044-Breedable-Polar-Bears.patch)

**Comment by duplexsystem** [comment]
0069-Configurable-TPS-Catchup.patch

**Comment by duplexsystem** [comment]
0094-Phantoms-attracted-to-crystals-and-crystals-shoot-ph.patch

**Comment by Disguys** [comment]
0097-Add-phantom-spawning-options.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0097-Add-phantom-spawning-options.patch)

**Comment by ghost** [comment]
0124-Add-option-to-disable-dolphin-treasure-searching.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0124-Add-option-to-disable-dolphin-treasure-searching.patch)

0123-Add-no-tick-block-list.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0123-Add-no-tick-block-list.patch)

0122-Allow-anvil-colors.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0122-Allow-anvil-colors.patch)

0120-PaperMC-Buffer-joins.patch - [Link](https://github.com/pl3xgaming/Purpur/blob/ver/1.16/patches/server/0120-PaperMC-Buffer-joins.patch)

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/57656020206f8ba4a04d6a3155c3f82fac426a56
