### ISSUE TITLE
Boats are buggy in Yatopia.

### ISSUE THREAD

**Issue by mibby** [tr7zw/YAPFA#377]
**Expected behavior**
Singleplayer-like entity collision with boats.

**Observed behavior**
When you hop out of a boat and plop out on top, you are colliding with the boat and can't move. Same as if you spawn a boat and try jumping on it. Your collision freaks out and locks up (stuttery/laggy).

**Steps to reproduce (if known)**
* Spawn boat.
* Get in. Get out.
* On top, can't move around.

**Installed plugins**
None.

**Version**
git-Yatopia-dev/threaded-worldgen-"6e8c4fa"

**Additional context**
Vanilla clean environment, stock configs.

**Comment by ishland** [comment]
Can confirm on both `ver/1.16.5` branch and purpur

**Comment by ishland** [comment]
Related to https://github.com/PaperMC/Paper/issues/5113

**Comment by Titaniumtown** [comment]
I saw in the tuinity discord server that this is actually a bug originating from Tuinity. So I will close this issue in favor of an issue being opened over there.

**Comment by mibby** [comment]
Someone in the Tuinity issue tracker mentioned removing Tuinity's ``0035-Optimise-collision-checking-in-player-move-packet-ha.patch`` patch fixes the behavior. Would it be possible to temporarily hotfix this / remove the patch until fixed upstream?

**Comment by LaurenceBarnes** [comment]
it exists on Paper too though, did they implement that patch?
