### ISSUE TITLE
Endermen run into the water

### ISSUE THREAD

**Issue by toinouH** [tr7zw/YAPFA#391]
**Expected behavior**
They should not run into water

**Observed behavior+Steps to reproduce**
https://youtu.be/BKf2vQFamkI

**Installed plugins**
https://imgur.com/a/7XQXNL6

**Version**
Discovered in git-Yatopia-"483c794" (MC: 1.16.2) and is still an issue on 1.16.5

Thanks @Disguys

**Comment by ishland** [comment]
Related to https://github.com/PaperMC/Paper/issues/5178

**Comment by Titaniumtown** [comment]
Closing as this is a vanilla issue and can be resolved upstream by Paper.
