### ISSUE TITLE
Ability to select if entities can teleport with portal

### ISSUE THREAD

**Issue by Baterka** [tr7zw/YAPFA#402]
**Describe what do you want us to implement**
Add ability to enable entity (other than player) teleportation trough Nether portals.
From my research all of main forks I tested (Spigot, Trinity, Paper, Origami, Purpur) do not have this feature disabled and teleportation of entities works fine.

**Is your feature request related to a problem**
Entities (eg. sheep) is not teleported when tyouches nether portal.

Tested on clean install of server without plugins and latest Yatopia (#27)

**Comment by Titaniumtown** [comment]
Purpur has this and so do we: https://pl3xgaming.github.io/PurpurDocs/Configuration/#entities-can-use-portals
It's in `purpur.yml`
