### ISSUE TITLE
the grass does not grow (it's not parametr about grass-spread-tick-rate)

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#406]
**Expected behavior**
Standart 

**Observed behavior**
Screenshot of the observed problem - https://imgur.com/a/HcStDyK
The grass has stopped growing, parametr grass-spread-tick-rate is set to 1

**Steps to reproduce (if known)**
Install blocks of earth and grass nearby, make sure they do not grow

**Installed plugins**
https://imgur.com/a/irghZdC

**Version**
Yatopia 1.16.5 build 26

**Comment by tommasobenatti** [comment]
I'm running the latest `dev/threaded-worldgen` with `grass-spread-tick-rate` set to 4 and I have the same issue

**Comment by tommasobenatti** [comment]
I'm running the latest `dev/threaded-worldgen` with grass-spread-tick-rate set to 4 and I don't have this issue https://i.imgur.com/lHHMfto.png

**Comment by Titaniumtown** [comment]
I believe this is an Airplane issue.

**Comment by pr1kol-zz** [comment]
Yes, the same problem, on these screenshots I waited more than 5 minutes when I tested. 
First on version 26 - https://imgur.com/KDlYGgH
Second on version 27 - https://imgur.com/qIZ79ZO

**Comment by Titaniumtown** [comment]
Closing in favor of: https://github.com/Technove/Airplane/issues/10

**Comment by Disguys** [comment]
@Titaniumtown has the problem been fixed?

**Comment by metabrixkt** [comment]
> @Titaniumtown has the problem been fixed?

Yes. PR with the fix was merged... yesterday as I remember.
