### ISSUE TITLE
Exceeded world limit

### ISSUE THREAD

**Issue by bobhenl** [tr7zw/YAPFA#416]
**Expected behavior**
 
Hi, I expect normally joining from servers on proxy to my Survival server, so for ex. that I could normally join from Lobby to Survival, but I couldn't.
**Observed behavior**

Hi, I couldn't connect from my proxy to Survival server due to I exceeded worlds limit few days ago. DO you think that you could increase or disable this world limit?

**Steps to reproduce (if known)**

1. Have more than 132 worlds.
2. Have proxy enabled.
3. Try to join from another server
![image](https://user-images.githubusercontent.com/18662086/108394858-7784be80-7215-11eb-86a5-cb39fde25f04.png)
![image](https://user-images.githubusercontent.com/18662086/108394867-7bb0dc00-7215-11eb-9d23-419808c37420.png)
Any error on Survival, just reconnecting messages
**Installed plugins**

They aren't needed, it's just due to this. But plugin that "caused" this is https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-nether-and-the-end-support-async-loading-expiration-1-8-1-16-4.72113/updates, this is why I have so many worlds. But it's good plugin then,.
**Version**

![image](https://user-images.githubusercontent.com/18662086/108394792-650a8500-7215-11eb-9ccb-036754a66d72.png)

**Timings**

Isn't needed
**Additional context**

**Comment by Titaniumtown** [comment]
Can you reproduce upstream? Have you tried with another plugin?

**Comment by toinouH** [comment]
@Titaniumtown it's useless https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/Login.java#L56

**Comment by toinouH** [comment]
I do not know if one fork of Bungeecord or Velocity fix that issue. I'll have to investigate.

**Comment by bobhenl** [comment]
Something new? It could solve few my issues 😅

**Comment by bobhenl** [comment]
Solved in bungeecord
