### ISSUE TITLE
Crash in pvp

### ISSUE THREAD

**Issue by Malachiel87** [tr7zw/YAPFA#423]
**Observed behavior**
A player was fighting  in pvp he died and was ressurected by totem and i got this weird message on console https://pastebin.com/UB7hiBAX and the player crashed 
 
**Installed plugins**
ChatControl, CMI, CMILib, CMIPaperLib, CombatLogX, CommandForward, CoreProtect, LPX*, LuckPerms, MobFarmManager, Nicky*, OreAnnouncer, PlaceholderAPI, Plan, ProtocolLib, spark, Swapper*, Trollcheat*, Vault, WorldBorder, WorldEdit, WorldGuard

**Version**
[23:55:34 INFO]: This server is running Yatopia version git-Yatopia-ver/1.16.5-24 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[23:55:34 INFO]: Previous version: git-Yatopia-"f8c5c21" (MC: 1.16.5)
[23:55:34 INFO]: You are 9 version(s) behind

**Comment by tommasobenatti** [comment]
Have you tried build 33?

**Comment by toinouH** [comment]
@Malachiel87 The pastebin has been deleted, do you still have the text and the issue (on the latest) ?

**Comment by Titaniumtown** [comment]
I'm just going to close this as we've gotten no response or logs.
