### ISSUE TITLE
Something wrong with Chunk loading?

### ISSUE THREAD

**Issue by flololan** [tr7zw/YAPFA#425]
I am not entirely sure if this is yatopias fault but I just saw that the server crashed and the last messages were the following:

```
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] ------------------------------
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] Server thread dump (Look for plugins here before reporting to Yatopia!):
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] ------------------------------
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] Current Thread: Server thread
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] PID: 27 | Suspended: false | Native: false | State: RUNNABLE
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] Suspected Plugins: None
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] Stack:
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:356)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAtIfLoadedMainThreadNoCache(ChunkProviderServer.java:110)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:1018)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:776)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.PlayerChunk$$Lambda$4988/0x00000008018b7458.run(Unknown Source)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:146)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:786)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:183)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:812)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1214)
[Tue, 2. Mar 2021 16:06:17 UTC ERROR] app//net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:805)
```

**Installed plugins**
- BetterSleeping
- ChestShop
- CoreProtect
- DiscordSRV
- dynmap
- EssentialsX
- EssentialsXAntiBuild
- EssentialsXChat
- EssentialsXProtect
- EssentialsXSpawn
- GriefPrevention
- HolographicDisplays
- LuckPerms
- Vault
- worldedit
- worldguard

**Version**
![grafik](https://user-images.githubusercontent.com/12832544/109682339-9d4b8500-7b7e-11eb-8bf4-8523e3eb6aab.png)

**Additional context**
Server is running on an VPS Docker environment using the image from [itzg](https://github.com/itzg/docker-minecraft-server). There are 50 GB of RAM available to the server.

**Comment by Titaniumtown** [comment]
Send full logs via https://paste.gg and see if you can reproduce on the latest build.

**Comment by flololan** [comment]
Ok I'll look if I can reproduce but for now I am not really sure what caused it. Here the full log: https://paste.gg/p/anonymous/684e371105c5479ca27ef6dcf5841aee

**Comment by Titaniumtown** [comment]
Try on the latest build, see if you can reproduce there too.

**Comment by flololan** [comment]
I'll try, if you have an idea what might have caused it I would be grateful for your ideas. As the server is constantly being used I would like to keep changes to a minimum as I am hosting for an local association and the server is almost never empty.

**Comment by toinouH** [comment]
@flololan does it occur on the latest build ?

**Comment by flololan** [comment]
> 
> 
> @flololan does it occur on the latest build ?

As I don't know what caused it I am still unable to reproduce it, independent from the build.

**Comment by Titaniumtown** [comment]
On the latest build, we now have Tuinity's rewrite of the chunk loading system. Does that solve the issue?

**Comment by flololan** [comment]
I will see if it happens again and if necessary come back. Thanks for your support
