### ISSUE TITLE
Players spawn in the void after they leave the server

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#426]
**Expected behavior**
The players on the server, once they leave the server, if they re-enter they can spawn in the void. This happens both in the overworld and in the end.

**Observed behavior**
If you exit the server in front of the end portal, randomly a user could spawn at the next join below in the void.

**Steps to reproduce (if known)**
Idk

**Version**
Version 33 - 1.16.5

**Comment by a8underscore** [comment]
what plugins do you have?

**Comment by metabrixkt** [comment]
@NovaPixell does it still happen?

Can you show `settings.checks` from `yatopia.yml`? If you have `moved-wrongly` check disabled, try enabling it and see.

**Comment by NovaPixell** [comment]
By activating all check-flights the problem does not occur
