### ISSUE TITLE
Prefer Rainforest over Papercut

### ISSUE THREAD

**Issue by Proximyst** [tr7zw/YAPFA#43]
Hi! I'm the lead developer of Papercut.

I've noticed you chose to include some of its patches, and just wanted to let you know we have *no* guarantee anything on it will work for others, and its patches may be very outdated.

Rainforest is my fork of Paper intended for developing patches such as async advancements for PR to Paper. It will have its patches updated as time goes and issues are found, but Papercut may not. I'm advising you switch to Rainforest instead for the patches you apply from Papercut.

**Comment by toinouH** [comment]
https://github.com/Proximyst/Rainforest

**Comment by duplexsystem** [comment]
Sounds good. I'll switch it over some time today!

**Comment by duplexsystem** [comment]
Fixed in Latest commit!
