### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [tr7zw/YAPFA#437]
![image](https://user-images.githubusercontent.com/43538462/111028855-b9aab580-83f9-11eb-850c-b8c9193164ba.png)
I am not able to build my plugin, some Yatopia dependency cause this error and cause build failure.

Used version:
![image](https://user-images.githubusercontent.com/43538462/111029003-9df3df00-83fa-11eb-93c3-65599ae4aef5.png)

Full maven error: 
![image](https://user-images.githubusercontent.com/43538462/111028892-ff677e00-83f9-11eb-8a58-67614d21290c.png)

**Comment by Tomut0** [comment]
I have the same problem.
Did you solve it?

**Comment by ghost** [comment]
> I have the same problem.
> Did you solve it?

Not yet

**Comment by toinouH** [comment]
@Stepa011 is it resolved now ?

**Comment by NoJokeFNA** [comment]
Did you also add the repository?
```
<repositories>
    <repository>
        <id>codemc-repo</id>
        <url>https://repo.codemc.io/repository/maven-public/</url>
    </repository>
</repositories>
```
