### ISSUE TITLE
An unknown error occurred and the server crashed, help! 

### ISSUE THREAD

**Issue by yurabens** [tr7zw/YAPFA#438]
When the server crashed, this information appeared in the console, I attach the console file. Can you help me understand what the problem is? p.s. I write through a translator, maybe not quite right. 
[console.txt](https://github.com/YatopiaMC/Yatopia/files/6136882/console.txt)

**Comment by Titaniumtown** [comment]
> --- DO NOT REPORT THIS TO YATOPIA - THIS IS NOT A BUG OR A CRASH  - git-Yatopia-"99e3c5d" (MC: 1.16.4) ---

Update your server

**Comment by yurabens** [comment]
My card works on version 1.16.4 - it is not possible to upgrade to 1.16.5
