### ISSUE TITLE
Licensing issue with Lithium-derived patches

### ISSUE THREAD

**Issue by silversquirl** [tr7zw/YAPFA#44]
Yatopia is licensed under MIT whereas Lithium is licensed under LGPL3.0. This causes an issue as any patches derived from Lithium code will need to be licensed under an LGPL3-compatible license, which MIT is not.

On further inspection, it seems like the Lithium-derived patches are correctly licensed under LGPL, however this should be more clearly stated in the LICENSE file, as currently it implies all the code in the repository is MIT-licensed. Additionally, the full text of the LGPL should be included in the repository, either in a separate file or in the relevant patches.

**Comment by duplexsystem** [comment]
Paper handles their Jellysqiud patch the same way.

**Comment by duplexsystem** [comment]
fixed in latest
