### ISSUE TITLE
Invisible players after changing world after first login.

### ISSUE THREAD

**Issue by PierlucaDP** [tr7zw/YAPFA#441]
**Expected behavior**
After a player's world change it should remain visible to all players.

**Observed behavior**
After a player's world change, it remains invisible to all players already on and visible to players who enter later.

**Steps to reproduce (if known)**
After some tests I noticed that immediately after the world change of a player entered for the first time it remains invisible, to make it visible again it's necessary to exit and re-enter (For the new player).

**Installed plugins**
Most plugins are custom plugins, none of them set a player's visibility. Even with all plugins disabled this problem occurs.

**Version**
This server is running YAPFA version git-YAPFA- "416314d" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
Even with all plugins disabled this problem occurs.

**Comment by metabrixkt** [comment]
@FreckledCoder Update to 1.16.5. 1.15.2 is no longer supported.
