### ISSUE TITLE
Exception ticking world (Server crashed)

### ISSUE THREAD

**Issue by luciobortoletto** [tr7zw/YAPFA#446]
**Expected behavior**
I expected the server not to crash.

**Observed behavior**
From the log: 
Horse (vehicle of MISERINI) moved wrongly!
Can't keep up! Is the server overloaded? Running 5126ms or 102 ticks behind,
then the server crashed.

**Steps to reproduce (if known)**
I don't know...

**Installed plugins**
Plugins (11): AFKPlus, AFKPlusPrefix, CoreProtect, JukeBox, NoteBlockAPI, OpenInv, SimpleTpa*, SkinsRestorer, ViaBackwards, ViaVersion, ViewDistanceTweaks.

**Version**
This server is running Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT).

**Timings**
How do I do this?

**Additional context**
It's not the first time this has happened.
Crash log: 
[crash-2021-03-29_21.38.44-server.txt](https://github.com/YatopiaMC/Yatopia/files/6237509/crash-2021-03-29_21.38.44-server.txt)

Sorry for the bad English!!!

**Comment by toinouH** [comment]
Could you confirm with the latest build ? https://github.com/YatopiaMC/Yatopia/actions/runs/695278461 (yatopia-11 in your case as you are using java11)

**Comment by luciobortoletto** [comment]
Now I try

**Comment by toinouH** [comment]
@luciobortoletto did it crash ?

**Comment by luciobortoletto** [comment]
Yesterday I closed the server. Today I try

**Comment by a8underscore** [comment]
hello did u try

**Comment by luciobortoletto** [comment]
Yes, I forgot to close the issue

**Comment by luciobortoletto** [comment]
It's fixed
