### ISSUE TITLE
Java 16 support

### ISSUE THREAD

**Issue by mokurin000** [tr7zw/YAPFA#449]
**Describe what do you want us to implement**

Support Java 16

**Additional context**

**Comment by toinouH** [comment]
Did you try with the latest build [https://github.com/YatopiaMC/Yatopia/actions/runs/695278461] ? (We need @sgdc3 for CodeMC)
In the case it's just a java version limitation: `-DPaper.IgnoreJavaVersion=true`

**Comment by mokurin000** [comment]
> ttps://github.com/YatopiaMC/Yatopia/actions/runs/695278461

I'm running [1.16.5 42](https://api.yatopiamc.org/v2/build/42/download?branch=ver/1.16.5)

It works with ` -DPaper.IgnoreJavaVersion=true ` now

**Comment by sgdc3** [comment]
CodeMC now has JDK16 support

**Comment by Titaniumtown** [comment]
you can just run java 15 jars on java 16, so no need.
