### ISSUE TITLE
Most plugins do not work

### ISSUE THREAD

**Issue by OndraCraft** [tr7zw/YAPFA#452]
After downloading and pasting on the server, more than half of the plugins stop working for me (They work on SSSpigot)

Discord support told me to create an issue on github and insert logs here

**Version**
https://github.com/YatopiaMC/Yatopia/actions/runs/720649246
Lastest build on Yatopia-11 (server running on java 11)

[2021-04-07-9.log.gz](https://github.com/YatopiaMC/Yatopia/files/6273555/2021-04-07-9.log.gz)

**Comment by OndraCraft** [comment]
Don't know what to do with it?

**Comment by NovaPixell** [comment]
Same, with HackedServer plugin

**Comment by Titaniumtown** [comment]
Known issue, it is being worked on (by me). I think I've found a culprit. but I need to dig a little deeper :)

**Comment by Fox2Code** [comment]
I have an idea on how to fix the `javassist` issues

But the 
```
Caused by: java.lang.NullPointerException
	at service.MetricsService.<init>(MetricsService.java:28) ~[?:?]
	at dev.j3fftw.litexpansion.LiteXpansion.<init>(LiteXpansion.java:26) ~[?:?]
```
Does not matching the latest GitHub source code
Please provide a download link matching the jar of your version of LiteXpansion

**Comment by TheArcaneBrony** [comment]
@Fox2Code the javassist issues are malware
redownload the plugins

**Comment by Titaniumtown** [comment]
Closing as this issue is malware-caused.
