### ISSUE TITLE
Creeper are not afraid of cats in a creeper farm

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#467]
**Expected behavior**
With the latest version of Yatopia creepers are not scared of cats

**Version**
This server is running Yatopia version git-Yatopia-ver/1.16.5-81 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Yatopia-ver/1.16.5-78 (MC: 1.16.5)
You are running the latest version

**Comment by Titaniumtown** [comment]
I can reproduce. I will look into this later :)

**Comment by Titaniumtown** [comment]
Working on figuring out the cause right now!

**Comment by Titaniumtown** [comment]
Update: `lithium AI` is the patch that causes the issue, I'm working on identifying what exactly in that patch is causing the issue.

**Comment by NovaPixell** [comment]
What is changed with the latest commit?

**Comment by Titaniumtown** [comment]
It's unrelated to this issue. It was just something I caught while I was looking though patches.
