### ISSUE TITLE
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

### ISSUE THREAD

**Issue by SurvivorsDev** [tr7zw/YAPFA#477]
**Version**
Yatopia-ver/1.16.5-96 (MC: 1.16.5)

**Additional context**
https://prnt.sc/12abvq3
https://stackoverflow.com/questions/53049346/is-log4j2-compatible-with-java-11

**Comment by Titaniumtown** [comment]
Ignore the warning.

**Comment by SurvivorsDev** [comment]
Well I got it, but still can you remove this warning with a new update?

**Comment by SurvivorsDev** [comment]
Can you remove the line here?
https://logging.apache.org/log4j/2.x/log4j-api/apidocs/src-html/org/apache/logging/log4j/util/StackLocator.html
System.out.println("WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.");

**Comment by Titaniumtown** [comment]
How.....

**Comment by SurvivorsDev** [comment]
Can you remove the warning message?

**Comment by TheDGOfficial** [comment]
Most probably updating log4j will fix this. Don't know why it happens on
Yatopia but not on Paper though, I looked into patches but couldn't find
anything related to it. Maybe one of the upstreams has this issue? I don't
have time to test right now but if one can test with them it would be good.

Özcan Erzurum ***@***.***>, 5 May 2021 Çar, 19:04 tarihinde
şunu yazdı:

**Comment by TheArcaneBrony** [comment]
I dont think its that important and can safely be ignored

**Comment by SurvivorsDev** [comment]
https://prnt.sc/12jehll

**Comment by SurvivorsDev** [comment]
https://prnt.sc/12jeq95

**Comment by TheArcaneBrony** [comment]
Cant really patch a dependency, regardless its safe to ignore
