### ISSUE TITLE
grass disappears

### ISSUE THREAD

**Issue by OceJlot** [tr7zw/YAPFA#489]
**Expected behavior**
 After +-15 min. on the server the grass accidentally disappears on spawn 

**Observed behavior**
 grass just disappears 
![image](https://user-images.githubusercontent.com/81906649/118361961-92f63000-b59e-11eb-99fb-e25a731cea09.png)

**Steps to reproduce (if known)**
download yatopia.jar / creating a start.bat file to run yatopia /  

**Installed plugins**
 0 plugins, just new yatopia  (On my server i have 1 plugin but i find this bug without any plugins

**Version**
![Снимок](https://user-images.githubusercontent.com/81906649/118361361-30039980-b59c-11eb-816c-cd14de289e03.PNG)

**Timings**
 https://timings.aikar.co/?id=bc5ae375ad8842adb4e004f5d7bcfbb4#timings

**Additional context**
-

**Comment by Creeperz653** [comment]
plugin list needed

**Comment by Titaniumtown** [comment]
Build 42 is not the latest
