### ISSUE TITLE
[Bug] Nether portal becomes a singular portal block

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#49]
**Describe the bug**
if you make a portal in the overworld, the portal in the nether, is just a singular "portal" block

**To Reproduce**
make a portal

**Expected behavior**
portal is created on other end

**Server Setup**
raspberry pi 4, arch linux arm, oc'd to 2ghz
![image](https://user-images.githubusercontent.com/11786225/89457268-1ee74b80-d733-11ea-8957-9ce9453dfd6f.png)

**Comment by duplexsystem** [comment]
Can you test this with the latest build

**Comment by Titaniumtown** [comment]
Will do

**Comment by Titaniumtown** [comment]
I will test it right now.
