### ISSUE TITLE
Ghost Blocks (Disapear After Restart)

### ISSUE THREAD

**Issue by greysilly7** [tr7zw/YAPFA#495]
**Expected behavior**
 
No ghost blocks at about 0-61 restarts
**Observed behavior**

There is ghost blocks every x restarts

**Steps to reproduce (if known)**

Restart a shit ton of times you will know its happened trust me
**Installed plugins**

None
**Version**

80-Latest
**Timings**

**Additional context**

Happens on build 80 and up

**Comment by greysilly7** [comment]
![image](https://user-images.githubusercontent.com/65827291/118741288-788db200-b83d-11eb-95af-ba50726db677.png)
That is what it looks like, Changes every time it happens

**Comment by PhantomG27249** [comment]
To anyone reading this issue: As far as we can tell the issue is non harmful and does no damage to the world and is solved after a restart. We are working to identify the cause but in the meantime if it occurs simply reboot the world the server and it should be "fixed"

**Comment by greysilly7** [comment]
Dosnt seem to be related to any of yatopias patches. because I had a build with all yatopia patches removed

**Comment by greysilly7** [comment]
With PR #497 from reports seems to happen arround 200 restarts now

**Comment by PhantomG27249** [comment]
thank you for confirming that the pr doesn't seem to fix it

**Comment by Kylepoops** [comment]
> With PR #497 from reports seems to happen arround 200 restarts now

Bruuhhhhhhh!

**Comment by PhantomG27249** [comment]
Should be fixed as of build 116
