### ISSUE TITLE
All blocks are saved to different states.

### ISSUE THREAD

**Issue by TheHappyHopper** [tr7zw/YAPFA#496]
**Expected behavior**
Blocks save properly

**Observed behavior**
every block gets saved as a different block

**Steps to reproduce (if known)**
Turn on server
Turn off server
Turn on server
All blocks are now different from their original state

**Installed plugins**
![2021-05-20_10 51 37](https://user-images.githubusercontent.com/66880702/119026681-4e7de200-b95a-11eb-98fb-15cef239a663.png)

**Version**
yatopia-1.16.5-paperclip-b115

**Comment by TheArcaneBrony** [comment]
It's not a save bug, restart the server. A fix is being worked on.

**Comment by Titaniumtown** [comment]
see #495 and #497
