### ISSUE TITLE
/tpsbar is not working in build#122

### ISSUE THREAD

**Issue by pthoelken** [tr7zw/YAPFA#509]
**Expected behavior**
/tpsbar shows the bar in top of your minecraft window

![image](https://user-images.githubusercontent.com/12643853/122208640-d98fc080-cea3-11eb-8e9e-4278705167e0.png)

**Observed behavior**
The command can not be found and tpsbar is not shown in [build-122](https://api.yatopiamc.org/v2/build/122/download?branch=ver/1.16.5). In [build-120](https://api.yatopiamc.org/v2/build/120/download?branch=ver/1.16.5) all is fine.

**Steps to reproduce (if known)**
Download the lastest [build-122](https://api.yatopiamc.org/v2/build/122/download?branch=ver/1.16.5) and start a normal server without plugins or something else. After login type in /tpsbar - nothing happens. If you switch back to [build-120](https://api.yatopiamc.org/v2/build/120/download?branch=ver/1.16.5) all works fine. 

**Installed plugins**
None

**Version**
```
[13:10:05 INFO]: Checking version, please wait...
[13:10:05 INFO]: This server is running Yatopia version git-Yatopia-ver/1.16.5-122 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 
Previous version: git-Yatopia-ver/1.16.5-120 (MC: 1.16.5)
You are running the latest version
```

**Additional context**
This is an problem / delete in the current build/patch because it's tested completly without plugins. The console shows no errors just the output, that the command is unkown.

**Comment by Toffikk** [comment]
It’s because we dropped purpur patches , there will be created a new branch with purpur patches later
