### ISSUE TITLE
[Bug] Dolphins dont move

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#57]
**Describe the bug**
Dolphins dont move
**To Reproduce**
look at dolphins

**Expected behavior**
dolphins move

**Server Setup**
raspberry pi 4, arch linux arm, oc'd to 2ghz

![image](https://user-images.githubusercontent.com/11786225/89595381-5aad0e80-d822-11ea-8469-0d736ea26d0d.png)

**Comment by duplexsystem** [comment]
reported fixed by @Titaniumtown
