### ISSUE TITLE
Hopper takes too long to collect the item

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#61]
I'm using the "81ec5ad" Yatopia build with OpenJ9. It seems that the hoppers catch the item after a long time.
![2020-08-07_22 04 57](https://user-images.githubusercontent.com/55632135/89685888-851fca00-d8fd-11ea-8137-0bb0693159e9.png)

**Comment by Titaniumtown** [comment]
Turn tick-empty-hoppers to true

**Comment by ghost** [comment]
> Turn tick-empty-hoppers to true

He did set it to true.

**Comment by NovaPixell** [comment]
> Turn tick-empty-hoppers to true

by default this value is set to true.

**Comment by NovaPixell** [comment]
fixed, disable tick-empty-hoppers
