### ISSUE TITLE
Add Sodium to side-upstreams

### ISSUE THREAD

**Issue by krolik-exe** [tr7zw/YAPFA#72]
Hi , i was wondering if this is posibble , if yes , then what about adding this to side upstreams , Like lithium?

**Comment by Obydux** [comment]
Sodium is a client side mod

**Comment by toinouH** [comment]
"Sodium is a free and open-source optimization mod **for the Minecraft client** that improves frame rates, reduces micro-stutter, and fixes graphical issues in Minecraft."
Source: https://github.com/jellysquid3/sodium-fabric
@krolik-exe , you can close the issue :)
