### ISSUE TITLE
[Bug] Flying squid, flying vine, dogs walk sitting

### ISSUE THREAD

**Issue by Disguys** [tr7zw/YAPFA#85]
**Describe the bug**
Flying squid, flying vine, dogs walk sitting

**Expected behavior**
Vanilla

**Additional context**
Flying squid screenshot - https://imgur.com/a/VC2FibC
Flying vine screenshot - https://imgur.com/a/w7Ksrnc
Dogs walk sitting video link (0:34) - https://youtu.be/ypLRoU1UnWM?t=34

**Comment by MrIvanPlays** [comment]
> Flying squid

this will be fixed when we port more patches from purpur

> flying vine

is this after you upgraded to 1.16.2 or is also present at 1.16.1?

**Comment by Disguys** [comment]
@MrIvanPlays I haven't updated to 1.16.2 yet , this bug is happening on 1.16.1

**Comment by MrIvanPlays** [comment]
How did u reproduce the flying vines?

**Comment by Disguys** [comment]
@MrIvanPlays they were so generated when loading chunks, and I often come across them in the jungle

**Comment by Disguys** [comment]
in huge quantities

**Comment by MrIvanPlays** [comment]
> dogs walk sitting

looks like a problem with asynchronous pathfinder

**Comment by MrIvanPlays** [comment]
try build 446 for the dog walk sitting. should be resolved

**Comment by Disguys** [comment]
@MrIvanPlays where can I download this build?

**Comment by toinouH** [comment]
https://github.com/YatopiaMC/Yatopia/actions/runs/207578797 @Disguys

**Comment by Disguys** [comment]
I tested this build, well, this problem with dogs is still relevant there

**Comment by MrIvanPlays** [comment]
then idk, in 1.16.2 there are no such problems. you can close your server until builds become stable enough.

**Comment by MrIvanPlays** [comment]
Try this build for the dog walking when sitting
https://github.com/YatopiaMC/Yatopia/actions/runs/208759957
It is still the async pathfinder but it was getting applied the previous build.

**Comment by MrIvanPlays** [comment]
Actually test this build for both dog walking when sitting and flying squids https://github.com/YatopiaMC/Yatopia/actions/runs/208994582
make sure you have squids-immune-to-EAR in purpur.yml enabled or else there would still be flying squids

**Comment by Disguys** [comment]
@MrIvanPlays, hi. Sorry to keep you waiting so long for my answer, I was away. I tested this build and can say that dogs there were fixed, and about flying squids I will tell you later, since I have not updated the my server to the last build.

**Comment by duplexsystem** [comment]
you have to change the config to fix them.

**Comment by Disguys** [comment]
@budgidiere I know, I'm telling you that I haven't put the last build on my main server yet, I've only checked the dogs

**Comment by Disguys** [comment]
The problem with flying squids and dogs has been fixed, thank you @MrIvanPlays. I hope that you will find an error with the generation of flying vines and fix them. I close the subject.
