### ISSUE TITLE
[Bug] Hostile mobs don't move

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#89]
**Describe the bug**
No hostile mobs move on ver/1.16.2, breaking mob farms

**To Reproduce**
Look at any hostile mob.

**Expected behavior**
Hostile mobs should move around, like normal. 

Note: Mobs works with tuinity, just not with Yatopia, so it's not my settings.

**Comment by MrIvanPlays** [comment]
Can u reproduce with an upstream project?

**Comment by Titaniumtown** [comment]
What do you mean?

**Comment by MrIvanPlays** [comment]
Can u reproduce with paper or tuinity for example

**Comment by Titaniumtown** [comment]
`Note: Mobs works with tuinity, just not with Yatopia, so it's not my settings.`

**Comment by MrIvanPlays** [comment]
oh

**Comment by MrIvanPlays** [comment]
Now I see why. 
Patches from `patches/removed` get applied too which means async pathfinder gets applied too.

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/c1c4a95edccf6badcdff006dd120d9c910523d0f
