### ISSUE TITLE
Iron Golem Farm

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#9]
Hi, I point out that iron farms are not working properly. In practice, as you can see in the attached photo, the villagers should sleep for a moment and wake up. Except that they stand still at this point. With paper it worked .. mhh what could it be?
![2020-05-06_12 34 36](https://user-images.githubusercontent.com/55632135/81167709-f619b380-8f95-11ea-8078-cdfa2329f9b1.png)

**Comment by tr7zw** [comment]
Looks again like an outdated farm design? Had something simular that worked in 1.14 but the villagers seem unable to get into the beds in 1.15 https://tr7zw.dev/u/1588781634.png (this is again vanilla singleplayer). Also, they won't be able to work/go to bed while they have line of sight to the zombie I think.

**Comment by NovaPixell** [comment]
really strange but with the software paper it worked perfectly. I would add that the Villagers now go to bed sometimes but rarely, but the Farm still doesn't work

**Comment by tr7zw** [comment]
Again, you at least are missing that the villageres can work because of the zombie. https://tr7zw.dev/u/1588783130.jpg This farm used to work in 1.14 but doesn't on 1.15 because the villagers can't go to bed. Also you need some type of redstone that sometimes pushes something between zombie and villagers so they use their workstation.

**Comment by NovaPixell** [comment]
ah okk got it, can you link me a video tutorial of a farm that should work?

**Comment by tr7zw** [comment]
All 1.15.2 farms should all work(have yet to upgrade mine). Where is that design from, since that shouldn't even work on 1.14.4?

**Comment by tr7zw** [comment]
Changes in 20w19a

    Villagers can now spawn iron golems regardless of their profession status or latest working time

Good news 😅

**Comment by NovaPixell** [comment]
Really strange. I made this farm and it works, in fact the villagers go to sleep. But they don't spawn iron golems haha. Do you think there is something to change on spigot.yml and the like? I remember that I had put my hands in these configuration purposes
![2020-05-07_14 37 00](https://user-images.githubusercontent.com/55632135/81295219-5aa94100-9070-11ea-9bd6-932039412472.png)

**Comment by tr7zw** [comment]
Not all sleep correctly and they don't/can't work = no golems.

**Comment by NovaPixell** [comment]
Mhhh okay. But what design i must create?

**Comment by tr7zw** [comment]
I just did a quick fix of my iron farm, I'll update upstream yapfa and then do a quck test with that before posting.

**Comment by tr7zw** [comment]
https://tr7zw.dev/u/1588866292.jpg ok I get iron golems spawning on yapfa/paper/tuinity, but I have to say that the villagers behave more braindead on yapfa than usual(more or less don't walk at all?). It doesn't really help that 1.15 is way jankier in what villagers do.

**Comment by NovaPixell** [comment]
Mhh ok understood, but if I have not misunderstood (tell me if it is the other way sorry) you should release a build where the villagers system in a few words?
