### ISSUE TITLE
[Bug] Animals can jump over fences

### ISSUE THREAD

**Issue by Titaniumtown** [tr7zw/YAPFA#97]
**Describe the bug**
Animals can jump over fences
**To Reproduce**
Make an animal farm with fences

**Expected behavior**
animals should be confined in the fences

**Comment by MrIvanPlays** [comment]
Can u reproduce with an upstream project?

Edit: NVM, found the cause of the issue

**Comment by MrIvanPlays** [comment]
https://github.com/YatopiaMC/Yatopia/commit/e9ca6e37c8aae862a15f555aab57d4b5a2ded2ee
